package cn.catarc.jsundials.nvecserial;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.DoubleByReference;
import com.sun.jna.ptr.LongByReference;
import com.sun.jna.ptr.PointerByReference;
import java.nio.DoubleBuffer;
import java.nio.LongBuffer;
/**
 * JNA Wrapper for library <b>sundials_nvecserial</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface Sundials_nvecserialLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "sundials_nvecserial";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(Sundials_nvecserialLibrary.JNA_LIBRARY_NAME);
	public static final Sundials_nvecserialLibrary INSTANCE = (Sundials_nvecserialLibrary)Native.loadLibrary(Sundials_nvecserialLibrary.JNA_LIBRARY_NAME, Sundials_nvecserialLibrary.class);
	/**
	 * -----------------------------------------------------------------<br>
	 * Functions exported by nvector_serial<br>
	 * -----------------------------------------------------------------<br>
	 * Original signature : <code>N_Vector N_VNewEmpty_Serial(sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:85</i><br>
	 * @deprecated use the safer methods {@link #N_VNewEmpty_Serial(long, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.SUNContext)} and {@link #N_VNewEmpty_Serial(long, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_nvecserialLibrary.N_Vector N_VNewEmpty_Serial(long vec_length, Pointer sunctx);
	/**
	 * -----------------------------------------------------------------<br>
	 * Functions exported by nvector_serial<br>
	 * -----------------------------------------------------------------<br>
	 * Original signature : <code>N_Vector N_VNewEmpty_Serial(sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:85</i>
	 */
	Sundials_nvecserialLibrary.N_Vector N_VNewEmpty_Serial(long vec_length, Sundials_nvecserialLibrary.SUNContext sunctx);
	/**
	 * Original signature : <code>N_Vector N_VNew_Serial(sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:88</i><br>
	 * @deprecated use the safer methods {@link #N_VNew_Serial(long, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.SUNContext)} and {@link #N_VNew_Serial(long, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_nvecserialLibrary.N_Vector N_VNew_Serial(long vec_length, Pointer sunctx);
	/**
	 * Original signature : <code>N_Vector N_VNew_Serial(sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:88</i>
	 */
	Sundials_nvecserialLibrary.N_Vector N_VNew_Serial(long vec_length, Sundials_nvecserialLibrary.SUNContext sunctx);
	/**
	 * Original signature : <code>N_Vector N_VMake_Serial(sunindextype, sunrealtype*, SUNContext)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:91</i><br>
	 * @deprecated use the safer methods {@link #N_VMake_Serial(long, java.nio.DoubleBuffer, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.SUNContext)} and {@link #N_VMake_Serial(long, com.sun.jna.ptr.DoubleByReference, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_nvecserialLibrary.N_Vector N_VMake_Serial(long vec_length, DoubleByReference v_data, Pointer sunctx);
	/**
	 * Original signature : <code>N_Vector N_VMake_Serial(sunindextype, sunrealtype*, SUNContext)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:91</i>
	 */
	Sundials_nvecserialLibrary.N_Vector N_VMake_Serial(long vec_length, DoubleBuffer v_data, Sundials_nvecserialLibrary.SUNContext sunctx);
	/**
	 * Original signature : <code>sunindextype N_VGetLength_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:95</i><br>
	 * @deprecated use the safer methods {@link #N_VGetLength_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VGetLength_Serial(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long N_VGetLength_Serial(Pointer v);
	/**
	 * Original signature : <code>sunindextype N_VGetLength_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:95</i>
	 */
	long N_VGetLength_Serial(Sundials_nvecserialLibrary.N_Vector v);
	/**
	 * Original signature : <code>void N_VPrint_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:98</i><br>
	 * @deprecated use the safer methods {@link #N_VPrint_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VPrint_Serial(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void N_VPrint_Serial(Pointer v);
	/**
	 * Original signature : <code>void N_VPrint_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:98</i>
	 */
	void N_VPrint_Serial(Sundials_nvecserialLibrary.N_Vector v);
	/**
	 * Original signature : <code>void N_VPrintFile_Serial(N_Vector, FILE*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:101</i><br>
	 * @deprecated use the safer methods {@link #N_VPrintFile_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, com.sun.jna.ptr.PointerByReference)} and {@link #N_VPrintFile_Serial(com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void N_VPrintFile_Serial(Pointer v, Pointer outfile);
	/**
	 * Original signature : <code>void N_VPrintFile_Serial(N_Vector, FILE*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:101</i>
	 */
	void N_VPrintFile_Serial(Sundials_nvecserialLibrary.N_Vector v, PointerByReference outfile);
	/**
	 * Original signature : <code>void N_VPrintFile_Serial(N_Vector, FILE*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:101</i>
	 */
	void N_VPrintFile_Serial(Pointer v, PointerByReference outfile);
	/**
	 * Original signature : <code>N_Vector_ID N_VGetVectorID_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:104</i><br>
	 * @deprecated use the safer methods {@link #N_VGetVectorID_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VGetVectorID_Serial(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int N_VGetVectorID_Serial(Pointer v);
	/**
	 * Original signature : <code>N_Vector_ID N_VGetVectorID_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:104</i>
	 */
	int N_VGetVectorID_Serial(Sundials_nvecserialLibrary.N_Vector v);
	/**
	 * Original signature : <code>N_Vector N_VCloneEmpty_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:109</i><br>
	 * @deprecated use the safer methods {@link #N_VCloneEmpty_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VCloneEmpty_Serial(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_nvecserialLibrary.N_Vector N_VCloneEmpty_Serial(Pointer w);
	/**
	 * Original signature : <code>N_Vector N_VCloneEmpty_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:109</i>
	 */
	Sundials_nvecserialLibrary.N_Vector N_VCloneEmpty_Serial(Sundials_nvecserialLibrary.N_Vector w);
	/**
	 * Original signature : <code>N_Vector N_VClone_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:112</i><br>
	 * @deprecated use the safer methods {@link #N_VClone_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VClone_Serial(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_nvecserialLibrary.N_Vector N_VClone_Serial(Pointer w);
	/**
	 * Original signature : <code>N_Vector N_VClone_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:112</i>
	 */
	Sundials_nvecserialLibrary.N_Vector N_VClone_Serial(Sundials_nvecserialLibrary.N_Vector w);
	/**
	 * Original signature : <code>void N_VDestroy_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:115</i><br>
	 * @deprecated use the safer methods {@link #N_VDestroy_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VDestroy_Serial(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void N_VDestroy_Serial(Pointer v);
	/**
	 * Original signature : <code>void N_VDestroy_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:115</i>
	 */
	void N_VDestroy_Serial(Sundials_nvecserialLibrary.N_Vector v);
	/**
	 * Original signature : <code>void N_VSpace_Serial(N_Vector, sunindextype*, sunindextype*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:118</i><br>
	 * @deprecated use the safer methods {@link #N_VSpace_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, java.nio.LongBuffer, java.nio.LongBuffer)} and {@link #N_VSpace_Serial(com.sun.jna.Pointer, com.sun.jna.ptr.LongByReference, com.sun.jna.ptr.LongByReference)} instead
	 */
	@Deprecated 
	void N_VSpace_Serial(Pointer v, LongByReference lrw, LongByReference liw);
	/**
	 * Original signature : <code>void N_VSpace_Serial(N_Vector, sunindextype*, sunindextype*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:118</i>
	 */
	void N_VSpace_Serial(Sundials_nvecserialLibrary.N_Vector v, LongBuffer lrw, LongBuffer liw);
	/**
	 * Original signature : <code>sunrealtype* N_VGetArrayPointer_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:121</i><br>
	 * @deprecated use the safer methods {@link #N_VGetArrayPointer_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VGetArrayPointer_Serial(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	DoubleByReference N_VGetArrayPointer_Serial(Pointer v);
	/**
	 * Original signature : <code>sunrealtype* N_VGetArrayPointer_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:121</i>
	 */
	DoubleByReference N_VGetArrayPointer_Serial(Sundials_nvecserialLibrary.N_Vector v);
	/**
	 * Original signature : <code>void N_VSetArrayPointer_Serial(sunrealtype*, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:124</i><br>
	 * @deprecated use the safer methods {@link #N_VSetArrayPointer_Serial(java.nio.DoubleBuffer, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VSetArrayPointer_Serial(com.sun.jna.ptr.DoubleByReference, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void N_VSetArrayPointer_Serial(DoubleByReference v_data, Pointer v);
	/**
	 * Original signature : <code>void N_VSetArrayPointer_Serial(sunrealtype*, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:124</i>
	 */
	void N_VSetArrayPointer_Serial(DoubleBuffer v_data, Sundials_nvecserialLibrary.N_Vector v);
	/**
	 * standard vector operations<br>
	 * Original signature : <code>void N_VLinearSum_Serial(sunrealtype, N_Vector, sunrealtype, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:128</i><br>
	 * @deprecated use the safer methods {@link #N_VLinearSum_Serial(double, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, double, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VLinearSum_Serial(double, com.sun.jna.Pointer, double, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void N_VLinearSum_Serial(double a, Pointer x, double b, Pointer y, Pointer z);
	/**
	 * standard vector operations<br>
	 * Original signature : <code>void N_VLinearSum_Serial(sunrealtype, N_Vector, sunrealtype, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:128</i>
	 */
	void N_VLinearSum_Serial(double a, Sundials_nvecserialLibrary.N_Vector x, double b, Sundials_nvecserialLibrary.N_Vector y, Sundials_nvecserialLibrary.N_Vector z);
	/**
	 * Original signature : <code>void N_VConst_Serial(sunrealtype, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:131</i><br>
	 * @deprecated use the safer methods {@link #N_VConst_Serial(double, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VConst_Serial(double, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void N_VConst_Serial(double c, Pointer z);
	/**
	 * Original signature : <code>void N_VConst_Serial(sunrealtype, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:131</i>
	 */
	void N_VConst_Serial(double c, Sundials_nvecserialLibrary.N_Vector z);
	/**
	 * Original signature : <code>void N_VProd_Serial(N_Vector, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:134</i><br>
	 * @deprecated use the safer methods {@link #N_VProd_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VProd_Serial(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void N_VProd_Serial(Pointer x, Pointer y, Pointer z);
	/**
	 * Original signature : <code>void N_VProd_Serial(N_Vector, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:134</i>
	 */
	void N_VProd_Serial(Sundials_nvecserialLibrary.N_Vector x, Sundials_nvecserialLibrary.N_Vector y, Sundials_nvecserialLibrary.N_Vector z);
	/**
	 * Original signature : <code>void N_VDiv_Serial(N_Vector, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:137</i><br>
	 * @deprecated use the safer methods {@link #N_VDiv_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VDiv_Serial(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void N_VDiv_Serial(Pointer x, Pointer y, Pointer z);
	/**
	 * Original signature : <code>void N_VDiv_Serial(N_Vector, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:137</i>
	 */
	void N_VDiv_Serial(Sundials_nvecserialLibrary.N_Vector x, Sundials_nvecserialLibrary.N_Vector y, Sundials_nvecserialLibrary.N_Vector z);
	/**
	 * Original signature : <code>void N_VScale_Serial(sunrealtype, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:140</i><br>
	 * @deprecated use the safer methods {@link #N_VScale_Serial(double, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VScale_Serial(double, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void N_VScale_Serial(double c, Pointer x, Pointer z);
	/**
	 * Original signature : <code>void N_VScale_Serial(sunrealtype, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:140</i>
	 */
	void N_VScale_Serial(double c, Sundials_nvecserialLibrary.N_Vector x, Sundials_nvecserialLibrary.N_Vector z);
	/**
	 * Original signature : <code>void N_VAbs_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:143</i><br>
	 * @deprecated use the safer methods {@link #N_VAbs_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VAbs_Serial(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void N_VAbs_Serial(Pointer x, Pointer z);
	/**
	 * Original signature : <code>void N_VAbs_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:143</i>
	 */
	void N_VAbs_Serial(Sundials_nvecserialLibrary.N_Vector x, Sundials_nvecserialLibrary.N_Vector z);
	/**
	 * Original signature : <code>void N_VInv_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:146</i><br>
	 * @deprecated use the safer methods {@link #N_VInv_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VInv_Serial(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void N_VInv_Serial(Pointer x, Pointer z);
	/**
	 * Original signature : <code>void N_VInv_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:146</i>
	 */
	void N_VInv_Serial(Sundials_nvecserialLibrary.N_Vector x, Sundials_nvecserialLibrary.N_Vector z);
	/**
	 * Original signature : <code>void N_VAddConst_Serial(N_Vector, sunrealtype, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:149</i><br>
	 * @deprecated use the safer methods {@link #N_VAddConst_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, double, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VAddConst_Serial(com.sun.jna.Pointer, double, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void N_VAddConst_Serial(Pointer x, double b, Pointer z);
	/**
	 * Original signature : <code>void N_VAddConst_Serial(N_Vector, sunrealtype, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:149</i>
	 */
	void N_VAddConst_Serial(Sundials_nvecserialLibrary.N_Vector x, double b, Sundials_nvecserialLibrary.N_Vector z);
	/**
	 * Original signature : <code>sunrealtype N_VDotProd_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:152</i><br>
	 * @deprecated use the safer methods {@link #N_VDotProd_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VDotProd_Serial(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	double N_VDotProd_Serial(Pointer x, Pointer y);
	/**
	 * Original signature : <code>sunrealtype N_VDotProd_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:152</i>
	 */
	double N_VDotProd_Serial(Sundials_nvecserialLibrary.N_Vector x, Sundials_nvecserialLibrary.N_Vector y);
	/**
	 * Original signature : <code>sunrealtype N_VMaxNorm_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:155</i><br>
	 * @deprecated use the safer methods {@link #N_VMaxNorm_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VMaxNorm_Serial(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	double N_VMaxNorm_Serial(Pointer x);
	/**
	 * Original signature : <code>sunrealtype N_VMaxNorm_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:155</i>
	 */
	double N_VMaxNorm_Serial(Sundials_nvecserialLibrary.N_Vector x);
	/**
	 * Original signature : <code>sunrealtype N_VWrmsNorm_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:158</i><br>
	 * @deprecated use the safer methods {@link #N_VWrmsNorm_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VWrmsNorm_Serial(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	double N_VWrmsNorm_Serial(Pointer x, Pointer w);
	/**
	 * Original signature : <code>sunrealtype N_VWrmsNorm_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:158</i>
	 */
	double N_VWrmsNorm_Serial(Sundials_nvecserialLibrary.N_Vector x, Sundials_nvecserialLibrary.N_Vector w);
	/**
	 * Original signature : <code>sunrealtype N_VWrmsNormMask_Serial(N_Vector, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:161</i><br>
	 * @deprecated use the safer methods {@link #N_VWrmsNormMask_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VWrmsNormMask_Serial(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	double N_VWrmsNormMask_Serial(Pointer x, Pointer w, Pointer id);
	/**
	 * Original signature : <code>sunrealtype N_VWrmsNormMask_Serial(N_Vector, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:161</i>
	 */
	double N_VWrmsNormMask_Serial(Sundials_nvecserialLibrary.N_Vector x, Sundials_nvecserialLibrary.N_Vector w, Sundials_nvecserialLibrary.N_Vector id);
	/**
	 * Original signature : <code>sunrealtype N_VMin_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:164</i><br>
	 * @deprecated use the safer methods {@link #N_VMin_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VMin_Serial(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	double N_VMin_Serial(Pointer x);
	/**
	 * Original signature : <code>sunrealtype N_VMin_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:164</i>
	 */
	double N_VMin_Serial(Sundials_nvecserialLibrary.N_Vector x);
	/**
	 * Original signature : <code>sunrealtype N_VWL2Norm_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:167</i><br>
	 * @deprecated use the safer methods {@link #N_VWL2Norm_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VWL2Norm_Serial(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	double N_VWL2Norm_Serial(Pointer x, Pointer w);
	/**
	 * Original signature : <code>sunrealtype N_VWL2Norm_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:167</i>
	 */
	double N_VWL2Norm_Serial(Sundials_nvecserialLibrary.N_Vector x, Sundials_nvecserialLibrary.N_Vector w);
	/**
	 * Original signature : <code>sunrealtype N_VL1Norm_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:170</i><br>
	 * @deprecated use the safer methods {@link #N_VL1Norm_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VL1Norm_Serial(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	double N_VL1Norm_Serial(Pointer x);
	/**
	 * Original signature : <code>sunrealtype N_VL1Norm_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:170</i>
	 */
	double N_VL1Norm_Serial(Sundials_nvecserialLibrary.N_Vector x);
	/**
	 * Original signature : <code>void N_VCompare_Serial(sunrealtype, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:173</i><br>
	 * @deprecated use the safer methods {@link #N_VCompare_Serial(double, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VCompare_Serial(double, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void N_VCompare_Serial(double c, Pointer x, Pointer z);
	/**
	 * Original signature : <code>void N_VCompare_Serial(sunrealtype, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:173</i>
	 */
	void N_VCompare_Serial(double c, Sundials_nvecserialLibrary.N_Vector x, Sundials_nvecserialLibrary.N_Vector z);
	/**
	 * Original signature : <code>int N_VInvTest_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:176</i><br>
	 * @deprecated use the safer methods {@link #N_VInvTest_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VInvTest_Serial(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int N_VInvTest_Serial(Pointer x, Pointer z);
	/**
	 * Original signature : <code>int N_VInvTest_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:176</i>
	 */
	int N_VInvTest_Serial(Sundials_nvecserialLibrary.N_Vector x, Sundials_nvecserialLibrary.N_Vector z);
	/**
	 * Original signature : <code>int N_VConstrMask_Serial(N_Vector, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:179</i><br>
	 * @deprecated use the safer methods {@link #N_VConstrMask_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VConstrMask_Serial(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int N_VConstrMask_Serial(Pointer c, Pointer x, Pointer m);
	/**
	 * Original signature : <code>int N_VConstrMask_Serial(N_Vector, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:179</i>
	 */
	int N_VConstrMask_Serial(Sundials_nvecserialLibrary.N_Vector c, Sundials_nvecserialLibrary.N_Vector x, Sundials_nvecserialLibrary.N_Vector m);
	/**
	 * Original signature : <code>sunrealtype N_VMinQuotient_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:182</i><br>
	 * @deprecated use the safer methods {@link #N_VMinQuotient_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VMinQuotient_Serial(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	double N_VMinQuotient_Serial(Pointer num, Pointer denom);
	/**
	 * Original signature : <code>sunrealtype N_VMinQuotient_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:182</i>
	 */
	double N_VMinQuotient_Serial(Sundials_nvecserialLibrary.N_Vector num, Sundials_nvecserialLibrary.N_Vector denom);
	/**
	 * fused vector operations<br>
	 * Original signature : <code>SUNErrCode N_VLinearCombination_Serial(int, sunrealtype*, N_Vector*, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:186</i><br>
	 * @deprecated use the safer methods {@link #N_VLinearCombination_Serial(int, java.nio.DoubleBuffer, com.sun.jna.ptr.PointerByReference, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VLinearCombination_Serial(int, com.sun.jna.ptr.DoubleByReference, com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int N_VLinearCombination_Serial(int nvec, DoubleByReference c, Pointer V, Pointer z);
	/**
	 * fused vector operations<br>
	 * Original signature : <code>SUNErrCode N_VLinearCombination_Serial(int, sunrealtype*, N_Vector*, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:186</i>
	 */
	int N_VLinearCombination_Serial(int nvec, DoubleBuffer c, PointerByReference V, Sundials_nvecserialLibrary.N_Vector z);
	/**
	 * fused vector operations<br>
	 * Original signature : <code>SUNErrCode N_VLinearCombination_Serial(int, sunrealtype*, N_Vector*, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:186</i>
	 */
	int N_VLinearCombination_Serial(int nvec, DoubleByReference c, PointerByReference V, Pointer z);
	/**
	 * Original signature : <code>SUNErrCode N_VScaleAddMulti_Serial(int, sunrealtype*, N_Vector, N_Vector*, N_Vector*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:189</i><br>
	 * @deprecated use the safer methods {@link #N_VScaleAddMulti_Serial(int, java.nio.DoubleBuffer, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} and {@link #N_VScaleAddMulti_Serial(int, com.sun.jna.ptr.DoubleByReference, com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int N_VScaleAddMulti_Serial(int nvec, DoubleByReference a, Pointer x, Pointer Y, Pointer Z);
	/**
	 * Original signature : <code>SUNErrCode N_VScaleAddMulti_Serial(int, sunrealtype*, N_Vector, N_Vector*, N_Vector*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:189</i>
	 */
	int N_VScaleAddMulti_Serial(int nvec, DoubleBuffer a, Sundials_nvecserialLibrary.N_Vector x, PointerByReference Y, PointerByReference Z);
	/**
	 * Original signature : <code>SUNErrCode N_VScaleAddMulti_Serial(int, sunrealtype*, N_Vector, N_Vector*, N_Vector*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:189</i>
	 */
	int N_VScaleAddMulti_Serial(int nvec, DoubleByReference a, Pointer x, PointerByReference Y, PointerByReference Z);
	/**
	 * Original signature : <code>SUNErrCode N_VDotProdMulti_Serial(int, N_Vector, N_Vector*, sunrealtype*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:192</i><br>
	 * @deprecated use the safer methods {@link #N_VDotProdMulti_Serial(int, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, com.sun.jna.ptr.PointerByReference, java.nio.DoubleBuffer)} and {@link #N_VDotProdMulti_Serial(int, com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Deprecated 
	int N_VDotProdMulti_Serial(int nvec, Pointer x, Pointer Y, DoubleByReference dotprods);
	/**
	 * Original signature : <code>SUNErrCode N_VDotProdMulti_Serial(int, N_Vector, N_Vector*, sunrealtype*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:192</i>
	 */
	int N_VDotProdMulti_Serial(int nvec, Sundials_nvecserialLibrary.N_Vector x, PointerByReference Y, DoubleBuffer dotprods);
	/**
	 * Original signature : <code>SUNErrCode N_VDotProdMulti_Serial(int, N_Vector, N_Vector*, sunrealtype*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:192</i>
	 */
	int N_VDotProdMulti_Serial(int nvec, Pointer x, PointerByReference Y, DoubleByReference dotprods);
	/**
	 * vector array operations<br>
	 * Original signature : <code>SUNErrCode N_VLinearSumVectorArray_Serial(int, sunrealtype, N_Vector*, sunrealtype, N_Vector*, N_Vector*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:197</i><br>
	 * @deprecated use the safer method {@link #N_VLinearSumVectorArray_Serial(int, double, com.sun.jna.ptr.PointerByReference, double, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int N_VLinearSumVectorArray_Serial(int nvec, double a, Pointer X, double b, Pointer Y, Pointer Z);
	/**
	 * vector array operations<br>
	 * Original signature : <code>SUNErrCode N_VLinearSumVectorArray_Serial(int, sunrealtype, N_Vector*, sunrealtype, N_Vector*, N_Vector*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:197</i>
	 */
	int N_VLinearSumVectorArray_Serial(int nvec, double a, PointerByReference X, double b, PointerByReference Y, PointerByReference Z);
	/**
	 * Original signature : <code>SUNErrCode N_VScaleVectorArray_Serial(int, sunrealtype*, N_Vector*, N_Vector*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:202</i><br>
	 * @deprecated use the safer methods {@link #N_VScaleVectorArray_Serial(int, java.nio.DoubleBuffer, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} and {@link #N_VScaleVectorArray_Serial(int, com.sun.jna.ptr.DoubleByReference, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int N_VScaleVectorArray_Serial(int nvec, DoubleByReference c, Pointer X, Pointer Z);
	/**
	 * Original signature : <code>SUNErrCode N_VScaleVectorArray_Serial(int, sunrealtype*, N_Vector*, N_Vector*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:202</i>
	 */
	int N_VScaleVectorArray_Serial(int nvec, DoubleBuffer c, PointerByReference X, PointerByReference Z);
	/**
	 * Original signature : <code>SUNErrCode N_VScaleVectorArray_Serial(int, sunrealtype*, N_Vector*, N_Vector*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:202</i>
	 */
	int N_VScaleVectorArray_Serial(int nvec, DoubleByReference c, PointerByReference X, PointerByReference Z);
	/**
	 * Original signature : <code>SUNErrCode N_VConstVectorArray_Serial(int, sunrealtype, N_Vector*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:206</i><br>
	 * @deprecated use the safer method {@link #N_VConstVectorArray_Serial(int, double, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int N_VConstVectorArray_Serial(int nvecs, double c, Pointer Z);
	/**
	 * Original signature : <code>SUNErrCode N_VConstVectorArray_Serial(int, sunrealtype, N_Vector*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:206</i>
	 */
	int N_VConstVectorArray_Serial(int nvecs, double c, PointerByReference Z);
	/**
	 * Original signature : <code>SUNErrCode N_VWrmsNormVectorArray_Serial(int, N_Vector*, N_Vector*, sunrealtype*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:209</i><br>
	 * @deprecated use the safer methods {@link #N_VWrmsNormVectorArray_Serial(int, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, java.nio.DoubleBuffer)} and {@link #N_VWrmsNormVectorArray_Serial(int, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Deprecated 
	int N_VWrmsNormVectorArray_Serial(int nvecs, Pointer X, Pointer W, DoubleByReference nrm);
	/**
	 * Original signature : <code>SUNErrCode N_VWrmsNormVectorArray_Serial(int, N_Vector*, N_Vector*, sunrealtype*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:209</i>
	 */
	int N_VWrmsNormVectorArray_Serial(int nvecs, PointerByReference X, PointerByReference W, DoubleBuffer nrm);
	/**
	 * Original signature : <code>SUNErrCode N_VWrmsNormVectorArray_Serial(int, N_Vector*, N_Vector*, sunrealtype*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:209</i>
	 */
	int N_VWrmsNormVectorArray_Serial(int nvecs, PointerByReference X, PointerByReference W, DoubleByReference nrm);
	/**
	 * Original signature : <code>SUNErrCode N_VWrmsNormMaskVectorArray_Serial(int, N_Vector*, N_Vector*, N_Vector, sunrealtype*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:213</i><br>
	 * @deprecated use the safer methods {@link #N_VWrmsNormMaskVectorArray_Serial(int, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, java.nio.DoubleBuffer)} and {@link #N_VWrmsNormMaskVectorArray_Serial(int, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Deprecated 
	int N_VWrmsNormMaskVectorArray_Serial(int nvecs, Pointer X, Pointer W, Pointer id, DoubleByReference nrm);
	/**
	 * Original signature : <code>SUNErrCode N_VWrmsNormMaskVectorArray_Serial(int, N_Vector*, N_Vector*, N_Vector, sunrealtype*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:213</i>
	 */
	int N_VWrmsNormMaskVectorArray_Serial(int nvecs, PointerByReference X, PointerByReference W, Sundials_nvecserialLibrary.N_Vector id, DoubleBuffer nrm);
	/**
	 * Original signature : <code>SUNErrCode N_VWrmsNormMaskVectorArray_Serial(int, N_Vector*, N_Vector*, N_Vector, sunrealtype*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:213</i>
	 */
	int N_VWrmsNormMaskVectorArray_Serial(int nvecs, PointerByReference X, PointerByReference W, Pointer id, DoubleByReference nrm);
	/**
	 * Original signature : <code>SUNErrCode N_VScaleAddMultiVectorArray_Serial(int, int, sunrealtype*, N_Vector*, N_Vector**, N_Vector**)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:217</i><br>
	 * @deprecated use the safer methods {@link #N_VScaleAddMultiVectorArray_Serial(int, int, java.nio.DoubleBuffer, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} and {@link #N_VScaleAddMultiVectorArray_Serial(int, int, com.sun.jna.ptr.DoubleByReference, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int N_VScaleAddMultiVectorArray_Serial(int nvec, int nsum, DoubleByReference a, Pointer X, PointerByReference Y, PointerByReference Z);
	/**
	 * Original signature : <code>SUNErrCode N_VScaleAddMultiVectorArray_Serial(int, int, sunrealtype*, N_Vector*, N_Vector**, N_Vector**)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:217</i>
	 */
	int N_VScaleAddMultiVectorArray_Serial(int nvec, int nsum, DoubleBuffer a, PointerByReference X, PointerByReference Y, PointerByReference Z);
	/**
	 * Original signature : <code>SUNErrCode N_VScaleAddMultiVectorArray_Serial(int, int, sunrealtype*, N_Vector*, N_Vector**, N_Vector**)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:217</i>
	 */
	int N_VScaleAddMultiVectorArray_Serial(int nvec, int nsum, DoubleByReference a, PointerByReference X, PointerByReference Y, PointerByReference Z);
	/**
	 * Original signature : <code>SUNErrCode N_VLinearCombinationVectorArray_Serial(int, int, sunrealtype*, N_Vector**, N_Vector*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:222</i><br>
	 * @deprecated use the safer methods {@link #N_VLinearCombinationVectorArray_Serial(int, int, java.nio.DoubleBuffer, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} and {@link #N_VLinearCombinationVectorArray_Serial(int, int, com.sun.jna.ptr.DoubleByReference, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int N_VLinearCombinationVectorArray_Serial(int nvec, int nsum, DoubleByReference c, PointerByReference X, Pointer Z);
	/**
	 * Original signature : <code>SUNErrCode N_VLinearCombinationVectorArray_Serial(int, int, sunrealtype*, N_Vector**, N_Vector*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:222</i>
	 */
	int N_VLinearCombinationVectorArray_Serial(int nvec, int nsum, DoubleBuffer c, PointerByReference X, PointerByReference Z);
	/**
	 * Original signature : <code>SUNErrCode N_VLinearCombinationVectorArray_Serial(int, int, sunrealtype*, N_Vector**, N_Vector*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:222</i>
	 */
	int N_VLinearCombinationVectorArray_Serial(int nvec, int nsum, DoubleByReference c, PointerByReference X, PointerByReference Z);
	/**
	 * OPTIONAL local reduction kernels (no parallel communication)<br>
	 * Original signature : <code>sunrealtype N_VWSqrSumLocal_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:228</i><br>
	 * @deprecated use the safer methods {@link #N_VWSqrSumLocal_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VWSqrSumLocal_Serial(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	double N_VWSqrSumLocal_Serial(Pointer x, Pointer w);
	/**
	 * OPTIONAL local reduction kernels (no parallel communication)<br>
	 * Original signature : <code>sunrealtype N_VWSqrSumLocal_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:228</i>
	 */
	double N_VWSqrSumLocal_Serial(Sundials_nvecserialLibrary.N_Vector x, Sundials_nvecserialLibrary.N_Vector w);
	/**
	 * Original signature : <code>sunrealtype N_VWSqrSumMaskLocal_Serial(N_Vector, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:231</i><br>
	 * @deprecated use the safer methods {@link #N_VWSqrSumMaskLocal_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector)} and {@link #N_VWSqrSumMaskLocal_Serial(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	double N_VWSqrSumMaskLocal_Serial(Pointer x, Pointer w, Pointer id);
	/**
	 * Original signature : <code>sunrealtype N_VWSqrSumMaskLocal_Serial(N_Vector, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:231</i>
	 */
	double N_VWSqrSumMaskLocal_Serial(Sundials_nvecserialLibrary.N_Vector x, Sundials_nvecserialLibrary.N_Vector w, Sundials_nvecserialLibrary.N_Vector id);
	/**
	 * OPTIONAL XBraid interface operations<br>
	 * Original signature : <code>SUNErrCode N_VBufSize_Serial(N_Vector, sunindextype*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:235</i><br>
	 * @deprecated use the safer methods {@link #N_VBufSize_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, java.nio.LongBuffer)} and {@link #N_VBufSize_Serial(com.sun.jna.Pointer, com.sun.jna.ptr.LongByReference)} instead
	 */
	@Deprecated 
	int N_VBufSize_Serial(Pointer x, LongByReference size);
	/**
	 * OPTIONAL XBraid interface operations<br>
	 * Original signature : <code>SUNErrCode N_VBufSize_Serial(N_Vector, sunindextype*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:235</i>
	 */
	int N_VBufSize_Serial(Sundials_nvecserialLibrary.N_Vector x, LongBuffer size);
	/**
	 * Original signature : <code>SUNErrCode N_VBufPack_Serial(N_Vector, void*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:238</i><br>
	 * @deprecated use the safer methods {@link #N_VBufPack_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, com.sun.jna.Pointer)} and {@link #N_VBufPack_Serial(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int N_VBufPack_Serial(Pointer x, Pointer buf);
	/**
	 * Original signature : <code>SUNErrCode N_VBufPack_Serial(N_Vector, void*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:238</i>
	 */
	int N_VBufPack_Serial(Sundials_nvecserialLibrary.N_Vector x, Pointer buf);
	/**
	 * Original signature : <code>SUNErrCode N_VBufUnpack_Serial(N_Vector, void*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:241</i><br>
	 * @deprecated use the safer methods {@link #N_VBufUnpack_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, com.sun.jna.Pointer)} and {@link #N_VBufUnpack_Serial(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int N_VBufUnpack_Serial(Pointer x, Pointer buf);
	/**
	 * Original signature : <code>SUNErrCode N_VBufUnpack_Serial(N_Vector, void*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:241</i>
	 */
	int N_VBufUnpack_Serial(Sundials_nvecserialLibrary.N_Vector x, Pointer buf);
	/**
	 * -----------------------------------------------------------------<br>
	 * Enable / disable fused vector operations<br>
	 * -----------------------------------------------------------------<br>
	 * Original signature : <code>SUNErrCode N_VEnableFusedOps_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:250</i><br>
	 * @deprecated use the safer methods {@link #N_VEnableFusedOps_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, int)} and {@link #N_VEnableFusedOps_Serial(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int N_VEnableFusedOps_Serial(Pointer v, int tf);
	/**
	 * -----------------------------------------------------------------<br>
	 * Enable / disable fused vector operations<br>
	 * -----------------------------------------------------------------<br>
	 * Original signature : <code>SUNErrCode N_VEnableFusedOps_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:250</i>
	 */
	int N_VEnableFusedOps_Serial(Sundials_nvecserialLibrary.N_Vector v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableLinearCombination_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:253</i><br>
	 * @deprecated use the safer methods {@link #N_VEnableLinearCombination_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, int)} and {@link #N_VEnableLinearCombination_Serial(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int N_VEnableLinearCombination_Serial(Pointer v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableLinearCombination_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:253</i>
	 */
	int N_VEnableLinearCombination_Serial(Sundials_nvecserialLibrary.N_Vector v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableScaleAddMulti_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:256</i><br>
	 * @deprecated use the safer methods {@link #N_VEnableScaleAddMulti_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, int)} and {@link #N_VEnableScaleAddMulti_Serial(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int N_VEnableScaleAddMulti_Serial(Pointer v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableScaleAddMulti_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:256</i>
	 */
	int N_VEnableScaleAddMulti_Serial(Sundials_nvecserialLibrary.N_Vector v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableDotProdMulti_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:259</i><br>
	 * @deprecated use the safer methods {@link #N_VEnableDotProdMulti_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, int)} and {@link #N_VEnableDotProdMulti_Serial(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int N_VEnableDotProdMulti_Serial(Pointer v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableDotProdMulti_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:259</i>
	 */
	int N_VEnableDotProdMulti_Serial(Sundials_nvecserialLibrary.N_Vector v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableLinearSumVectorArray_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:262</i><br>
	 * @deprecated use the safer methods {@link #N_VEnableLinearSumVectorArray_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, int)} and {@link #N_VEnableLinearSumVectorArray_Serial(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int N_VEnableLinearSumVectorArray_Serial(Pointer v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableLinearSumVectorArray_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:262</i>
	 */
	int N_VEnableLinearSumVectorArray_Serial(Sundials_nvecserialLibrary.N_Vector v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableScaleVectorArray_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:265</i><br>
	 * @deprecated use the safer methods {@link #N_VEnableScaleVectorArray_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, int)} and {@link #N_VEnableScaleVectorArray_Serial(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int N_VEnableScaleVectorArray_Serial(Pointer v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableScaleVectorArray_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:265</i>
	 */
	int N_VEnableScaleVectorArray_Serial(Sundials_nvecserialLibrary.N_Vector v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableConstVectorArray_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:268</i><br>
	 * @deprecated use the safer methods {@link #N_VEnableConstVectorArray_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, int)} and {@link #N_VEnableConstVectorArray_Serial(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int N_VEnableConstVectorArray_Serial(Pointer v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableConstVectorArray_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:268</i>
	 */
	int N_VEnableConstVectorArray_Serial(Sundials_nvecserialLibrary.N_Vector v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableWrmsNormVectorArray_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:271</i><br>
	 * @deprecated use the safer methods {@link #N_VEnableWrmsNormVectorArray_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, int)} and {@link #N_VEnableWrmsNormVectorArray_Serial(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int N_VEnableWrmsNormVectorArray_Serial(Pointer v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableWrmsNormVectorArray_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:271</i>
	 */
	int N_VEnableWrmsNormVectorArray_Serial(Sundials_nvecserialLibrary.N_Vector v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableWrmsNormMaskVectorArray_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:274</i><br>
	 * @deprecated use the safer methods {@link #N_VEnableWrmsNormMaskVectorArray_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, int)} and {@link #N_VEnableWrmsNormMaskVectorArray_Serial(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int N_VEnableWrmsNormMaskVectorArray_Serial(Pointer v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableWrmsNormMaskVectorArray_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:274</i>
	 */
	int N_VEnableWrmsNormMaskVectorArray_Serial(Sundials_nvecserialLibrary.N_Vector v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableScaleAddMultiVectorArray_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:277</i><br>
	 * @deprecated use the safer methods {@link #N_VEnableScaleAddMultiVectorArray_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, int)} and {@link #N_VEnableScaleAddMultiVectorArray_Serial(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int N_VEnableScaleAddMultiVectorArray_Serial(Pointer v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableScaleAddMultiVectorArray_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:277</i>
	 */
	int N_VEnableScaleAddMultiVectorArray_Serial(Sundials_nvecserialLibrary.N_Vector v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableLinearCombinationVectorArray_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:281</i><br>
	 * @deprecated use the safer methods {@link #N_VEnableLinearCombinationVectorArray_Serial(cn.catarc.jsundials.nvecserial.Sundials_nvecserialLibrary.N_Vector, int)} and {@link #N_VEnableLinearCombinationVectorArray_Serial(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int N_VEnableLinearCombinationVectorArray_Serial(Pointer v, int tf);
	/**
	 * Original signature : <code>SUNErrCode N_VEnableLinearCombinationVectorArray_Serial(N_Vector, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:281</i>
	 */
	int N_VEnableLinearCombinationVectorArray_Serial(Sundials_nvecserialLibrary.N_Vector v, int tf);
	public static class SUNContext extends PointerType {
		public SUNContext(Pointer address) {
			super(address);
		}
		public SUNContext() {
			super();
		}
	};
	public static class FILE extends PointerType {
		public FILE(Pointer address) {
			super(address);
		}
		public FILE() {
			super();
		}
	};
	public static class N_Vector extends PointerType {
		public N_Vector(Pointer address) {
			super(address);
		}
		public N_Vector() {
			super();
		}
	};
}
