package cn.catarc.jsundials.arkode;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.DoubleByReference;
import com.sun.jna.ptr.PointerByReference;

import java.util.Arrays;
import java.util.List;
/**
 * ---------------------------------------------------------------<br>
 * Types : struct ARKodeButcherTableMem, ARKodeButcherTable<br>
 * ---------------------------------------------------------------<br>
 * <i>native declaration : include\arkode\arkode_butcher.h:29</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ARKodeButcherTableMem extends Structure {
	/** method order of accuracy */
	public int q;
	/** embedding order of accuracy */
	public int p;
	/** number of stages */
	public int stages;
	/**
	 * Butcher table coefficients<br>
	 * C type : sunrealtype**
	 */
	public PointerByReference A;
	/**
	 * canopy node coefficients<br>
	 * C type : sunrealtype*
	 */
	public DoubleByReference c;
	/**
	 * root node coefficients<br>
	 * C type : sunrealtype*
	 */
	public DoubleByReference b;
	/**
	 * embedding coefficients<br>
	 * C type : sunrealtype*
	 */
	public DoubleByReference d;
	public ARKodeButcherTableMem() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("q", "p", "stages", "A", "c", "b", "d");
	}
	/**
	 * @param q method order of accuracy<br>
	 * @param p embedding order of accuracy<br>
	 * @param stages number of stages<br>
	 * @param A Butcher table coefficients<br>
	 * C type : sunrealtype**<br>
	 * @param c canopy node coefficients<br>
	 * C type : sunrealtype*<br>
	 * @param b root node coefficients<br>
	 * C type : sunrealtype*<br>
	 * @param d embedding coefficients<br>
	 * C type : sunrealtype*
	 */
	public ARKodeButcherTableMem(int q, int p, int stages, PointerByReference A, DoubleByReference c, DoubleByReference b, DoubleByReference d) {
		super();
		this.q = q;
		this.p = p;
		this.stages = stages;
		this.A = A;
		this.c = c;
		this.b = b;
		this.d = d;
	}
	public ARKodeButcherTableMem(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ARKodeButcherTableMem implements Structure.ByReference {
		
	};
	public static class ByValue extends ARKodeButcherTableMem implements Structure.ByValue {
		
	};
}
