package cn.catarc.jsundials;

import com.sun.jna.*;
import com.sun.jna.ptr.LongByReference;

import java.nio.LongBuffer;
/**
 * JNA Wrapper for library <b>SundialsSunmatrixdense</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface SundialsSunmatrixdenseLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "SundialsSunmatrixdense";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(SundialsSunmatrixdenseLibrary.JNA_LIBRARY_NAME);
	public static final SundialsSunmatrixdenseLibrary INSTANCE = (SundialsSunmatrixdenseLibrary)Native.loadLibrary(SundialsSunmatrixdenseLibrary.JNA_LIBRARY_NAME, SundialsSunmatrixdenseLibrary.class);
	/**
	 * ---------------------------------------<br>
	 * Exported Functions for SUNMATRIX_DENSE<br>
	 * ---------------------------------------<br>
	 * Original signature : <code>SUNMatrix SUNDenseMatrix(sunindextype, sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:45</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix(sunindextype, sunindextype, SUNContext)} and {@link #SUNDenseMatrix(Pointer, Pointer, Pointer)} instead
	 */
	@Deprecated 
	SUNMatrix SUNDenseMatrix(Pointer M, Pointer N, Pointer sunctx);
	/**
	 * ---------------------------------------<br>
	 * Exported Functions for SUNMATRIX_DENSE<br>
	 * ---------------------------------------<br>
	 * Original signature : <code>SUNMatrix SUNDenseMatrix(sunindextype, sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:45</i>
	 */
	SUNMatrix SUNDenseMatrix(sunindextype M, sunindextype N, SUNContext sunctx);
	/**
	 * Original signature : <code>void SUNDenseMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:48</i>
	 */
	void SUNDenseMatrix_Print(SUNMatrix A, FILE outfile);
	/**
	 * Original signature : <code>sunindextype SUNDenseMatrix_Rows(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:50</i>
	 */
	sunindextype SUNDenseMatrix_Rows(SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNDenseMatrix_Columns(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:51</i>
	 */
	sunindextype SUNDenseMatrix_Columns(SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNDenseMatrix_LData(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:52</i>
	 */
	sunindextype SUNDenseMatrix_LData(SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype* SUNDenseMatrix_Data(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:53</i>
	 */
	sunrealtype SUNDenseMatrix_Data(SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype** SUNDenseMatrix_Cols(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:54</i>
	 */
	sunrealtype[] SUNDenseMatrix_Cols(SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype* SUNDenseMatrix_Column(SUNMatrix, sunindextype)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:55</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix_Column(SUNMatrix, sunindextype)} and {@link #SUNDenseMatrix_Column(SUNMatrix, Pointer)} instead
	 */
	@Deprecated 
	sunrealtype SUNDenseMatrix_Column(SUNMatrix A, Pointer j);
	/**
	 * Original signature : <code>sunrealtype* SUNDenseMatrix_Column(SUNMatrix, sunindextype)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:55</i>
	 */
	sunrealtype SUNDenseMatrix_Column(SUNMatrix A, sunindextype j);
	/**
	 * Original signature : <code>SUNMatrix_ID SUNMatGetID_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:57</i>
	 */
	int SUNMatGetID_Dense(SUNMatrix A);
	/**
	 * Original signature : <code>SUNMatrix SUNMatClone_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:58</i>
	 */
	SUNMatrix SUNMatClone_Dense(SUNMatrix A);
	/**
	 * Original signature : <code>void SUNMatDestroy_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:59</i>
	 */
	void SUNMatDestroy_Dense(SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatZero_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:60</i>
	 */
	int SUNMatZero_Dense(SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatCopy_Dense(SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:61</i>
	 */
	int SUNMatCopy_Dense(SUNMatrix A, SUNMatrix B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAdd_Dense(sunrealtype, SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:62</i>
	 */
	int SUNMatScaleAdd_Dense(sunrealtype c, SUNMatrix A, SUNMatrix B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAddI_Dense(sunrealtype, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:64</i>
	 */
	int SUNMatScaleAddI_Dense(sunrealtype c, SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatMatvec_Dense(SUNMatrix, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:65</i>
	 */
	int SUNMatMatvec_Dense(SUNMatrix A, N_Vector x, N_Vector y);
	/**
	 * Original signature : <code>SUNErrCode SUNMatSpace_Dense(SUNMatrix, long long*, long long*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:67</i><br>
	 * @deprecated use the safer methods {@link #SUNMatSpace_Dense(SUNMatrix, LongBuffer, LongBuffer)} and {@link #SUNMatSpace_Dense(SUNMatrix, LongByReference, LongByReference)} instead
	 */
	@Deprecated 
	int SUNMatSpace_Dense(SUNMatrix A, LongByReference lenrw, LongByReference leniw);
	/**
	 * Original signature : <code>SUNErrCode SUNMatSpace_Dense(SUNMatrix, long long*, long long*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:67</i>
	 */
	int SUNMatSpace_Dense(SUNMatrix A, LongBuffer lenrw, LongBuffer leniw);
	public static class SUNMatrix extends PointerType {
		public SUNMatrix(Pointer address) {
			super(address);
		}
		public SUNMatrix() {
			super();
		}
	};
	public static class SUNContext extends PointerType {
		public SUNContext(Pointer address) {
			super(address);
		}
		public SUNContext() {
			super();
		}
	};
	public static class sunrealtype extends PointerType {
		public sunrealtype(Pointer address) {
			super(address);
		}
		public sunrealtype() {
			super();
		}
	};
	public static class FILE extends PointerType {
		public FILE(Pointer address) {
			super(address);
		}
		public FILE() {
			super();
		}
	};
	public static class sunindextype extends PointerType {
		public sunindextype(Pointer address) {
			super(address);
		}
		public sunindextype() {
			super();
		}
	};
	public static class N_Vector extends PointerType {
		public N_Vector(Pointer address) {
			super(address);
		}
		public N_Vector() {
			super();
		}
	};
}
