package cn.catarc.jsundials.sunmatrixsparse;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.DoubleByReference;
import com.sun.jna.ptr.LongByReference;
import com.sun.jna.ptr.PointerByReference;
import java.util.Arrays;
import java.util.List;
/**
 * ------------------------------------------<br>
 * Sparse Implementation of SUNMATRIX_SPARSE<br>
 * ------------------------------------------<br>
 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:17</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class _SUNMatrixContent_Sparse extends Structure {
	/** C type : sunindextype */
	public long M;
	/** C type : sunindextype */
	public long N;
	/** C type : sunindextype */
	public long NNZ;
	/** C type : sunindextype */
	public long NP;
	/** C type : sunrealtype* */
	public DoubleByReference data;
	public int sparsetype;
	/** C type : sunindextype* */
	public LongByReference indexvals;
	/** C type : sunindextype* */
	public LongByReference indexptrs;
	/** C type : sunindextype** */
	public PointerByReference rowvals;
	/** C type : sunindextype** */
	public PointerByReference colptrs;
	/** C type : sunindextype** */
	public PointerByReference colvals;
	/** C type : sunindextype** */
	public PointerByReference rowptrs;
	public _SUNMatrixContent_Sparse() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("M", "N", "NNZ", "NP", "data", "sparsetype", "indexvals", "indexptrs", "rowvals", "colptrs", "colvals", "rowptrs");
	}
	public _SUNMatrixContent_Sparse(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends _SUNMatrixContent_Sparse implements Structure.ByReference {
		
	};
	public static class ByValue extends _SUNMatrixContent_Sparse implements Structure.ByValue {
		
	};
}
