package cn.catarc.jsundials.sunmatrixsparse;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.DoubleByReference;
import com.sun.jna.ptr.LongByReference;
import com.sun.jna.ptr.PointerByReference;
import java.nio.LongBuffer;
/**
 * JNA Wrapper for library <b>sundials_sunmatrixsparse</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface Sundials_sunmatrixsparseLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "sundials_sunmatrixsparse";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(Sundials_sunmatrixsparseLibrary.JNA_LIBRARY_NAME);
	public static final Sundials_sunmatrixsparseLibrary INSTANCE = (Sundials_sunmatrixsparseLibrary)Native.loadLibrary(Sundials_sunmatrixsparseLibrary.JNA_LIBRARY_NAME, Sundials_sunmatrixsparseLibrary.class);
	/** <i>native declaration : include\sunmatrix\sunmatrix_sparse.h</i> */
	public static final int CSC_MAT = (int)0;
	/** <i>native declaration : include\sunmatrix\sunmatrix_sparse.h</i> */
	public static final int CSR_MAT = (int)1;
	/**
	 * ----------------------------------------<br>
	 * Exported  Functions for SUNMATRIX_BAND<br>
	 * ----------------------------------------<br>
	 * Original signature : <code>SUNMatrix SUNBandMatrix(sunindextype, sunindextype, sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:60</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix(long, long, long, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNContext)} and {@link #SUNBandMatrix(long, long, long, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNBandMatrix(long N, long mu, long ml, Pointer sunctx);
	/**
	 * ----------------------------------------<br>
	 * Exported  Functions for SUNMATRIX_BAND<br>
	 * ----------------------------------------<br>
	 * Original signature : <code>SUNMatrix SUNBandMatrix(sunindextype, sunindextype, sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:60</i>
	 */
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNBandMatrix(long N, long mu, long ml, Sundials_sunmatrixsparseLibrary.SUNContext sunctx);
	/**
	 * Original signature : <code>SUNMatrix SUNBandMatrixStorage(sunindextype, sunindextype, sunindextype, sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:63</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrixStorage(long, long, long, long, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNContext)} and {@link #SUNBandMatrixStorage(long, long, long, long, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNBandMatrixStorage(long N, long mu, long ml, long smu, Pointer sunctx);
	/**
	 * Original signature : <code>SUNMatrix SUNBandMatrixStorage(sunindextype, sunindextype, sunindextype, sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:63</i>
	 */
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNBandMatrixStorage(long N, long mu, long ml, long smu, Sundials_sunmatrixsparseLibrary.SUNContext sunctx);
	/**
	 * Original signature : <code>void SUNBandMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:67</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_Print(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, com.sun.jna.ptr.PointerByReference)} and {@link #SUNBandMatrix_Print(com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void SUNBandMatrix_Print(Pointer A, Pointer outfile);
	/**
	 * Original signature : <code>void SUNBandMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:67</i>
	 */
	void SUNBandMatrix_Print(Sundials_sunmatrixsparseLibrary.SUNMatrix A, PointerByReference outfile);
	/**
	 * Original signature : <code>void SUNBandMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:67</i>
	 */
	void SUNBandMatrix_Print(Pointer A, PointerByReference outfile);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_Rows(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:69</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_Rows(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNBandMatrix_Rows(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNBandMatrix_Rows(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_Rows(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:69</i>
	 */
	long SUNBandMatrix_Rows(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_Columns(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:70</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_Columns(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNBandMatrix_Columns(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNBandMatrix_Columns(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_Columns(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:70</i>
	 */
	long SUNBandMatrix_Columns(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_LowerBandwidth(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:71</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_LowerBandwidth(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNBandMatrix_LowerBandwidth(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNBandMatrix_LowerBandwidth(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_LowerBandwidth(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:71</i>
	 */
	long SUNBandMatrix_LowerBandwidth(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_UpperBandwidth(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:72</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_UpperBandwidth(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNBandMatrix_UpperBandwidth(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNBandMatrix_UpperBandwidth(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_UpperBandwidth(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:72</i>
	 */
	long SUNBandMatrix_UpperBandwidth(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_StoredUpperBandwidth(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:73</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_StoredUpperBandwidth(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNBandMatrix_StoredUpperBandwidth(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNBandMatrix_StoredUpperBandwidth(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_StoredUpperBandwidth(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:73</i>
	 */
	long SUNBandMatrix_StoredUpperBandwidth(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_LDim(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:74</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_LDim(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNBandMatrix_LDim(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNBandMatrix_LDim(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_LDim(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:74</i>
	 */
	long SUNBandMatrix_LDim(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_LData(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:75</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_LData(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNBandMatrix_LData(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNBandMatrix_LData(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_LData(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:75</i>
	 */
	long SUNBandMatrix_LData(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype* SUNBandMatrix_Data(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:76</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_Data(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNBandMatrix_Data(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	DoubleByReference SUNBandMatrix_Data(Pointer A);
	/**
	 * Original signature : <code>sunrealtype* SUNBandMatrix_Data(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:76</i>
	 */
	DoubleByReference SUNBandMatrix_Data(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype** SUNBandMatrix_Cols(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:77</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_Cols(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNBandMatrix_Cols(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	PointerByReference SUNBandMatrix_Cols(Pointer A);
	/**
	 * Original signature : <code>sunrealtype** SUNBandMatrix_Cols(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:77</i>
	 */
	PointerByReference SUNBandMatrix_Cols(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype* SUNBandMatrix_Column(SUNMatrix, sunindextype)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:78</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_Column(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, long)} and {@link #SUNBandMatrix_Column(com.sun.jna.Pointer, long)} instead
	 */
	@Deprecated 
	DoubleByReference SUNBandMatrix_Column(Pointer A, long j);
	/**
	 * Original signature : <code>sunrealtype* SUNBandMatrix_Column(SUNMatrix, sunindextype)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:78</i>
	 */
	DoubleByReference SUNBandMatrix_Column(Sundials_sunmatrixsparseLibrary.SUNMatrix A, long j);
	/**
	 * Original signature : <code>SUNMatrix_ID SUNMatGetID_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:80</i><br>
	 * @deprecated use the safer methods {@link #SUNMatGetID_Band(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatGetID_Band(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatGetID_Band(Pointer A);
	/**
	 * Original signature : <code>SUNMatrix_ID SUNMatGetID_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:80</i>
	 */
	int SUNMatGetID_Band(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNMatrix SUNMatClone_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:81</i><br>
	 * @deprecated use the safer methods {@link #SUNMatClone_Band(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatClone_Band(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNMatClone_Band(Pointer A);
	/**
	 * Original signature : <code>SUNMatrix SUNMatClone_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:81</i>
	 */
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNMatClone_Band(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>void SUNMatDestroy_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:82</i><br>
	 * @deprecated use the safer methods {@link #SUNMatDestroy_Band(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatDestroy_Band(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void SUNMatDestroy_Band(Pointer A);
	/**
	 * Original signature : <code>void SUNMatDestroy_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:82</i>
	 */
	void SUNMatDestroy_Band(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatZero_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:83</i><br>
	 * @deprecated use the safer methods {@link #SUNMatZero_Band(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatZero_Band(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatZero_Band(Pointer A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatZero_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:83</i>
	 */
	int SUNMatZero_Band(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatCopy_Band(SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:84</i><br>
	 * @deprecated use the safer methods {@link #SUNMatCopy_Band(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatCopy_Band(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatCopy_Band(Pointer A, Pointer B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatCopy_Band(SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:84</i>
	 */
	int SUNMatCopy_Band(Sundials_sunmatrixsparseLibrary.SUNMatrix A, Sundials_sunmatrixsparseLibrary.SUNMatrix B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAdd_Band(sunrealtype, SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:85</i><br>
	 * @deprecated use the safer methods {@link #SUNMatScaleAdd_Band(double, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatScaleAdd_Band(double, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatScaleAdd_Band(double c, Pointer A, Pointer B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAdd_Band(sunrealtype, SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:85</i>
	 */
	int SUNMatScaleAdd_Band(double c, Sundials_sunmatrixsparseLibrary.SUNMatrix A, Sundials_sunmatrixsparseLibrary.SUNMatrix B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAddI_Band(sunrealtype, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:87</i><br>
	 * @deprecated use the safer methods {@link #SUNMatScaleAddI_Band(double, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatScaleAddI_Band(double, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatScaleAddI_Band(double c, Pointer A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAddI_Band(sunrealtype, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:87</i>
	 */
	int SUNMatScaleAddI_Band(double c, Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatMatvec_Band(SUNMatrix, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:88</i><br>
	 * @deprecated use the safer methods {@link #SUNMatMatvec_Band(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.N_Vector, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.N_Vector)} and {@link #SUNMatMatvec_Band(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatMatvec_Band(Pointer A, Pointer x, Pointer y);
	/**
	 * Original signature : <code>SUNErrCode SUNMatMatvec_Band(SUNMatrix, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:88</i>
	 */
	int SUNMatMatvec_Band(Sundials_sunmatrixsparseLibrary.SUNMatrix A, Sundials_sunmatrixsparseLibrary.N_Vector x, Sundials_sunmatrixsparseLibrary.N_Vector y);
	/**
	 * Original signature : <code>SUNErrCode SUNMatSpace_Band(SUNMatrix, long long*, long long*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:89</i><br>
	 * @deprecated use the safer methods {@link #SUNMatSpace_Band(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, java.nio.LongBuffer, java.nio.LongBuffer)} and {@link #SUNMatSpace_Band(com.sun.jna.Pointer, com.sun.jna.ptr.LongByReference, com.sun.jna.ptr.LongByReference)} instead
	 */
	@Deprecated 
	int SUNMatSpace_Band(Pointer A, LongByReference lenrw, LongByReference leniw);
	/**
	 * Original signature : <code>SUNErrCode SUNMatSpace_Band(SUNMatrix, long long*, long long*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:89</i>
	 */
	int SUNMatSpace_Band(Sundials_sunmatrixsparseLibrary.SUNMatrix A, LongBuffer lenrw, LongBuffer leniw);
	/**
	 * ---------------------------------------<br>
	 * Exported Functions for SUNMATRIX_DENSE<br>
	 * ---------------------------------------<br>
	 * Original signature : <code>SUNMatrix SUNDenseMatrix(sunindextype, sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:45</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix(long, long, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNContext)} and {@link #SUNDenseMatrix(long, long, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNDenseMatrix(long M, long N, Pointer sunctx);
	/**
	 * ---------------------------------------<br>
	 * Exported Functions for SUNMATRIX_DENSE<br>
	 * ---------------------------------------<br>
	 * Original signature : <code>SUNMatrix SUNDenseMatrix(sunindextype, sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:45</i>
	 */
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNDenseMatrix(long M, long N, Sundials_sunmatrixsparseLibrary.SUNContext sunctx);
	/**
	 * Original signature : <code>void SUNDenseMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:48</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix_Print(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, com.sun.jna.ptr.PointerByReference)} and {@link #SUNDenseMatrix_Print(com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void SUNDenseMatrix_Print(Pointer A, Pointer outfile);
	/**
	 * Original signature : <code>void SUNDenseMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:48</i>
	 */
	void SUNDenseMatrix_Print(Sundials_sunmatrixsparseLibrary.SUNMatrix A, PointerByReference outfile);
	/**
	 * Original signature : <code>void SUNDenseMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:48</i>
	 */
	void SUNDenseMatrix_Print(Pointer A, PointerByReference outfile);
	/**
	 * Original signature : <code>sunindextype SUNDenseMatrix_Rows(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:50</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix_Rows(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNDenseMatrix_Rows(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNDenseMatrix_Rows(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNDenseMatrix_Rows(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:50</i>
	 */
	long SUNDenseMatrix_Rows(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNDenseMatrix_Columns(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:51</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix_Columns(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNDenseMatrix_Columns(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNDenseMatrix_Columns(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNDenseMatrix_Columns(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:51</i>
	 */
	long SUNDenseMatrix_Columns(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNDenseMatrix_LData(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:52</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix_LData(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNDenseMatrix_LData(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNDenseMatrix_LData(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNDenseMatrix_LData(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:52</i>
	 */
	long SUNDenseMatrix_LData(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype* SUNDenseMatrix_Data(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:53</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix_Data(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNDenseMatrix_Data(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	DoubleByReference SUNDenseMatrix_Data(Pointer A);
	/**
	 * Original signature : <code>sunrealtype* SUNDenseMatrix_Data(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:53</i>
	 */
	DoubleByReference SUNDenseMatrix_Data(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype** SUNDenseMatrix_Cols(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:54</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix_Cols(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNDenseMatrix_Cols(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	PointerByReference SUNDenseMatrix_Cols(Pointer A);
	/**
	 * Original signature : <code>sunrealtype** SUNDenseMatrix_Cols(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:54</i>
	 */
	PointerByReference SUNDenseMatrix_Cols(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype* SUNDenseMatrix_Column(SUNMatrix, sunindextype)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:55</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix_Column(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, long)} and {@link #SUNDenseMatrix_Column(com.sun.jna.Pointer, long)} instead
	 */
	@Deprecated 
	DoubleByReference SUNDenseMatrix_Column(Pointer A, long j);
	/**
	 * Original signature : <code>sunrealtype* SUNDenseMatrix_Column(SUNMatrix, sunindextype)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:55</i>
	 */
	DoubleByReference SUNDenseMatrix_Column(Sundials_sunmatrixsparseLibrary.SUNMatrix A, long j);
	/**
	 * Original signature : <code>SUNMatrix_ID SUNMatGetID_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:57</i><br>
	 * @deprecated use the safer methods {@link #SUNMatGetID_Dense(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatGetID_Dense(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatGetID_Dense(Pointer A);
	/**
	 * Original signature : <code>SUNMatrix_ID SUNMatGetID_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:57</i>
	 */
	int SUNMatGetID_Dense(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNMatrix SUNMatClone_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:58</i><br>
	 * @deprecated use the safer methods {@link #SUNMatClone_Dense(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatClone_Dense(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNMatClone_Dense(Pointer A);
	/**
	 * Original signature : <code>SUNMatrix SUNMatClone_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:58</i>
	 */
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNMatClone_Dense(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>void SUNMatDestroy_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:59</i><br>
	 * @deprecated use the safer methods {@link #SUNMatDestroy_Dense(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatDestroy_Dense(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void SUNMatDestroy_Dense(Pointer A);
	/**
	 * Original signature : <code>void SUNMatDestroy_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:59</i>
	 */
	void SUNMatDestroy_Dense(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatZero_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:60</i><br>
	 * @deprecated use the safer methods {@link #SUNMatZero_Dense(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatZero_Dense(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatZero_Dense(Pointer A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatZero_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:60</i>
	 */
	int SUNMatZero_Dense(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatCopy_Dense(SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:61</i><br>
	 * @deprecated use the safer methods {@link #SUNMatCopy_Dense(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatCopy_Dense(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatCopy_Dense(Pointer A, Pointer B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatCopy_Dense(SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:61</i>
	 */
	int SUNMatCopy_Dense(Sundials_sunmatrixsparseLibrary.SUNMatrix A, Sundials_sunmatrixsparseLibrary.SUNMatrix B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAdd_Dense(sunrealtype, SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:62</i><br>
	 * @deprecated use the safer methods {@link #SUNMatScaleAdd_Dense(double, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatScaleAdd_Dense(double, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatScaleAdd_Dense(double c, Pointer A, Pointer B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAdd_Dense(sunrealtype, SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:62</i>
	 */
	int SUNMatScaleAdd_Dense(double c, Sundials_sunmatrixsparseLibrary.SUNMatrix A, Sundials_sunmatrixsparseLibrary.SUNMatrix B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAddI_Dense(sunrealtype, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:64</i><br>
	 * @deprecated use the safer methods {@link #SUNMatScaleAddI_Dense(double, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatScaleAddI_Dense(double, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatScaleAddI_Dense(double c, Pointer A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAddI_Dense(sunrealtype, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:64</i>
	 */
	int SUNMatScaleAddI_Dense(double c, Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatMatvec_Dense(SUNMatrix, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:65</i><br>
	 * @deprecated use the safer methods {@link #SUNMatMatvec_Dense(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.N_Vector, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.N_Vector)} and {@link #SUNMatMatvec_Dense(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatMatvec_Dense(Pointer A, Pointer x, Pointer y);
	/**
	 * Original signature : <code>SUNErrCode SUNMatMatvec_Dense(SUNMatrix, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:65</i>
	 */
	int SUNMatMatvec_Dense(Sundials_sunmatrixsparseLibrary.SUNMatrix A, Sundials_sunmatrixsparseLibrary.N_Vector x, Sundials_sunmatrixsparseLibrary.N_Vector y);
	/**
	 * Original signature : <code>SUNErrCode SUNMatSpace_Dense(SUNMatrix, long long*, long long*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:67</i><br>
	 * @deprecated use the safer methods {@link #SUNMatSpace_Dense(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, java.nio.LongBuffer, java.nio.LongBuffer)} and {@link #SUNMatSpace_Dense(com.sun.jna.Pointer, com.sun.jna.ptr.LongByReference, com.sun.jna.ptr.LongByReference)} instead
	 */
	@Deprecated 
	int SUNMatSpace_Dense(Pointer A, LongByReference lenrw, LongByReference leniw);
	/**
	 * Original signature : <code>SUNErrCode SUNMatSpace_Dense(SUNMatrix, long long*, long long*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:67</i>
	 */
	int SUNMatSpace_Dense(Sundials_sunmatrixsparseLibrary.SUNMatrix A, LongBuffer lenrw, LongBuffer leniw);
	/**
	 * ----------------------------------------<br>
	 * Exported Functions for SUNMATRIX_SPARSE<br>
	 * ----------------------------------------<br>
	 * Original signature : <code>SUNMatrix SUNSparseMatrix(sunindextype, sunindextype, sunindextype, int, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:63</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseMatrix(long, long, long, int, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNContext)} and {@link #SUNSparseMatrix(long, long, long, int, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNSparseMatrix(long M, long N, long NNZ, int sparsetype, Pointer sunctx);
	/**
	 * ----------------------------------------<br>
	 * Exported Functions for SUNMATRIX_SPARSE<br>
	 * ----------------------------------------<br>
	 * Original signature : <code>SUNMatrix SUNSparseMatrix(sunindextype, sunindextype, sunindextype, int, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:63</i>
	 */
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNSparseMatrix(long M, long N, long NNZ, int sparsetype, Sundials_sunmatrixsparseLibrary.SUNContext sunctx);
	/**
	 * Original signature : <code>SUNMatrix SUNSparseFromDenseMatrix(SUNMatrix, sunrealtype, int)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:67</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseFromDenseMatrix(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, double, int)} and {@link #SUNSparseFromDenseMatrix(com.sun.jna.Pointer, double, int)} instead
	 */
	@Deprecated 
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNSparseFromDenseMatrix(Pointer A, double droptol, int sparsetype);
	/**
	 * Original signature : <code>SUNMatrix SUNSparseFromDenseMatrix(SUNMatrix, sunrealtype, int)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:67</i>
	 */
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNSparseFromDenseMatrix(Sundials_sunmatrixsparseLibrary.SUNMatrix A, double droptol, int sparsetype);
	/**
	 * Original signature : <code>SUNMatrix SUNSparseFromBandMatrix(SUNMatrix, sunrealtype, int)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:71</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseFromBandMatrix(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, double, int)} and {@link #SUNSparseFromBandMatrix(com.sun.jna.Pointer, double, int)} instead
	 */
	@Deprecated 
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNSparseFromBandMatrix(Pointer A, double droptol, int sparsetype);
	/**
	 * Original signature : <code>SUNMatrix SUNSparseFromBandMatrix(SUNMatrix, sunrealtype, int)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:71</i>
	 */
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNSparseFromBandMatrix(Sundials_sunmatrixsparseLibrary.SUNMatrix A, double droptol, int sparsetype);
	/**
	 * Original signature : <code>SUNErrCode SUNSparseMatrix_ToCSR(const SUNMatrix, SUNMatrix*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:75</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseMatrix_ToCSR(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, com.sun.jna.ptr.PointerByReference)} and {@link #SUNSparseMatrix_ToCSR(com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int SUNSparseMatrix_ToCSR(Pointer A, Pointer Bout);
	/**
	 * Original signature : <code>SUNErrCode SUNSparseMatrix_ToCSR(const SUNMatrix, SUNMatrix*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:75</i>
	 */
	int SUNSparseMatrix_ToCSR(Sundials_sunmatrixsparseLibrary.SUNMatrix A, PointerByReference Bout);
	/**
	 * Original signature : <code>SUNErrCode SUNSparseMatrix_ToCSR(const SUNMatrix, SUNMatrix*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:75</i>
	 */
	int SUNSparseMatrix_ToCSR(Pointer A, PointerByReference Bout);
	/**
	 * Original signature : <code>SUNErrCode SUNSparseMatrix_ToCSC(const SUNMatrix, SUNMatrix*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:78</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseMatrix_ToCSC(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, com.sun.jna.ptr.PointerByReference)} and {@link #SUNSparseMatrix_ToCSC(com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int SUNSparseMatrix_ToCSC(Pointer A, Pointer Bout);
	/**
	 * Original signature : <code>SUNErrCode SUNSparseMatrix_ToCSC(const SUNMatrix, SUNMatrix*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:78</i>
	 */
	int SUNSparseMatrix_ToCSC(Sundials_sunmatrixsparseLibrary.SUNMatrix A, PointerByReference Bout);
	/**
	 * Original signature : <code>SUNErrCode SUNSparseMatrix_ToCSC(const SUNMatrix, SUNMatrix*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:78</i>
	 */
	int SUNSparseMatrix_ToCSC(Pointer A, PointerByReference Bout);
	/**
	 * Original signature : <code>SUNErrCode SUNSparseMatrix_Realloc(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:81</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseMatrix_Realloc(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNSparseMatrix_Realloc(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNSparseMatrix_Realloc(Pointer A);
	/**
	 * Original signature : <code>SUNErrCode SUNSparseMatrix_Realloc(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:81</i>
	 */
	int SUNSparseMatrix_Realloc(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNSparseMatrix_Reallocate(SUNMatrix, sunindextype)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:84</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseMatrix_Reallocate(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, long)} and {@link #SUNSparseMatrix_Reallocate(com.sun.jna.Pointer, long)} instead
	 */
	@Deprecated 
	int SUNSparseMatrix_Reallocate(Pointer A, long NNZ);
	/**
	 * Original signature : <code>SUNErrCode SUNSparseMatrix_Reallocate(SUNMatrix, sunindextype)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:84</i>
	 */
	int SUNSparseMatrix_Reallocate(Sundials_sunmatrixsparseLibrary.SUNMatrix A, long NNZ);
	/**
	 * Original signature : <code>void SUNSparseMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:87</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseMatrix_Print(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, com.sun.jna.ptr.PointerByReference)} and {@link #SUNSparseMatrix_Print(com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void SUNSparseMatrix_Print(Pointer A, Pointer outfile);
	/**
	 * Original signature : <code>void SUNSparseMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:87</i>
	 */
	void SUNSparseMatrix_Print(Sundials_sunmatrixsparseLibrary.SUNMatrix A, PointerByReference outfile);
	/**
	 * Original signature : <code>void SUNSparseMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:87</i>
	 */
	void SUNSparseMatrix_Print(Pointer A, PointerByReference outfile);
	/**
	 * Original signature : <code>sunindextype SUNSparseMatrix_Rows(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:90</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseMatrix_Rows(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNSparseMatrix_Rows(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNSparseMatrix_Rows(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNSparseMatrix_Rows(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:90</i>
	 */
	long SUNSparseMatrix_Rows(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNSparseMatrix_Columns(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:93</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseMatrix_Columns(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNSparseMatrix_Columns(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNSparseMatrix_Columns(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNSparseMatrix_Columns(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:93</i>
	 */
	long SUNSparseMatrix_Columns(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNSparseMatrix_NNZ(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:96</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseMatrix_NNZ(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNSparseMatrix_NNZ(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNSparseMatrix_NNZ(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNSparseMatrix_NNZ(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:96</i>
	 */
	long SUNSparseMatrix_NNZ(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNSparseMatrix_NP(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:99</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseMatrix_NP(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNSparseMatrix_NP(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNSparseMatrix_NP(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNSparseMatrix_NP(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:99</i>
	 */
	long SUNSparseMatrix_NP(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>int SUNSparseMatrix_SparseType(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:102</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseMatrix_SparseType(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNSparseMatrix_SparseType(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNSparseMatrix_SparseType(Pointer A);
	/**
	 * Original signature : <code>int SUNSparseMatrix_SparseType(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:102</i>
	 */
	int SUNSparseMatrix_SparseType(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype* SUNSparseMatrix_Data(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:105</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseMatrix_Data(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNSparseMatrix_Data(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	DoubleByReference SUNSparseMatrix_Data(Pointer A);
	/**
	 * Original signature : <code>sunrealtype* SUNSparseMatrix_Data(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:105</i>
	 */
	DoubleByReference SUNSparseMatrix_Data(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype* SUNSparseMatrix_IndexValues(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:108</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseMatrix_IndexValues(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNSparseMatrix_IndexValues(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	LongByReference SUNSparseMatrix_IndexValues(Pointer A);
	/**
	 * Original signature : <code>sunindextype* SUNSparseMatrix_IndexValues(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:108</i>
	 */
	LongByReference SUNSparseMatrix_IndexValues(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype* SUNSparseMatrix_IndexPointers(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:111</i><br>
	 * @deprecated use the safer methods {@link #SUNSparseMatrix_IndexPointers(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNSparseMatrix_IndexPointers(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	LongByReference SUNSparseMatrix_IndexPointers(Pointer A);
	/**
	 * Original signature : <code>sunindextype* SUNSparseMatrix_IndexPointers(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:111</i>
	 */
	LongByReference SUNSparseMatrix_IndexPointers(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNMatrix_ID SUNMatGetID_Sparse(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:114</i><br>
	 * @deprecated use the safer methods {@link #SUNMatGetID_Sparse(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatGetID_Sparse(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatGetID_Sparse(Pointer A);
	/**
	 * Original signature : <code>SUNMatrix_ID SUNMatGetID_Sparse(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:114</i>
	 */
	int SUNMatGetID_Sparse(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNMatrix SUNMatClone_Sparse(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:117</i><br>
	 * @deprecated use the safer methods {@link #SUNMatClone_Sparse(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatClone_Sparse(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNMatClone_Sparse(Pointer A);
	/**
	 * Original signature : <code>SUNMatrix SUNMatClone_Sparse(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:117</i>
	 */
	Sundials_sunmatrixsparseLibrary.SUNMatrix SUNMatClone_Sparse(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>void SUNMatDestroy_Sparse(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:120</i><br>
	 * @deprecated use the safer methods {@link #SUNMatDestroy_Sparse(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatDestroy_Sparse(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void SUNMatDestroy_Sparse(Pointer A);
	/**
	 * Original signature : <code>void SUNMatDestroy_Sparse(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:120</i>
	 */
	void SUNMatDestroy_Sparse(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatZero_Sparse(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:123</i><br>
	 * @deprecated use the safer methods {@link #SUNMatZero_Sparse(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatZero_Sparse(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatZero_Sparse(Pointer A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatZero_Sparse(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:123</i>
	 */
	int SUNMatZero_Sparse(Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatCopy_Sparse(SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:126</i><br>
	 * @deprecated use the safer methods {@link #SUNMatCopy_Sparse(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatCopy_Sparse(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatCopy_Sparse(Pointer A, Pointer B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatCopy_Sparse(SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:126</i>
	 */
	int SUNMatCopy_Sparse(Sundials_sunmatrixsparseLibrary.SUNMatrix A, Sundials_sunmatrixsparseLibrary.SUNMatrix B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAdd_Sparse(sunrealtype, SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:129</i><br>
	 * @deprecated use the safer methods {@link #SUNMatScaleAdd_Sparse(double, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatScaleAdd_Sparse(double, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatScaleAdd_Sparse(double c, Pointer A, Pointer B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAdd_Sparse(sunrealtype, SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:129</i>
	 */
	int SUNMatScaleAdd_Sparse(double c, Sundials_sunmatrixsparseLibrary.SUNMatrix A, Sundials_sunmatrixsparseLibrary.SUNMatrix B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAddI_Sparse(sunrealtype, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:132</i><br>
	 * @deprecated use the safer methods {@link #SUNMatScaleAddI_Sparse(double, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix)} and {@link #SUNMatScaleAddI_Sparse(double, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatScaleAddI_Sparse(double c, Pointer A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAddI_Sparse(sunrealtype, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:132</i>
	 */
	int SUNMatScaleAddI_Sparse(double c, Sundials_sunmatrixsparseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatMatvec_Sparse(SUNMatrix, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:135</i><br>
	 * @deprecated use the safer methods {@link #SUNMatMatvec_Sparse(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.N_Vector, cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.N_Vector)} and {@link #SUNMatMatvec_Sparse(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatMatvec_Sparse(Pointer A, Pointer x, Pointer y);
	/**
	 * Original signature : <code>SUNErrCode SUNMatMatvec_Sparse(SUNMatrix, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:135</i>
	 */
	int SUNMatMatvec_Sparse(Sundials_sunmatrixsparseLibrary.SUNMatrix A, Sundials_sunmatrixsparseLibrary.N_Vector x, Sundials_sunmatrixsparseLibrary.N_Vector y);
	/**
	 * Original signature : <code>SUNErrCode SUNMatSpace_Sparse(SUNMatrix, long long*, long long*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:138</i><br>
	 * @deprecated use the safer methods {@link #SUNMatSpace_Sparse(cn.catarc.jsundials.sunmatrixsparse.Sundials_sunmatrixsparseLibrary.SUNMatrix, java.nio.LongBuffer, java.nio.LongBuffer)} and {@link #SUNMatSpace_Sparse(com.sun.jna.Pointer, com.sun.jna.ptr.LongByReference, com.sun.jna.ptr.LongByReference)} instead
	 */
	@Deprecated 
	int SUNMatSpace_Sparse(Pointer A, LongByReference lenrw, LongByReference leniw);
	/**
	 * Original signature : <code>SUNErrCode SUNMatSpace_Sparse(SUNMatrix, long long*, long long*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_sparse.h:138</i>
	 */
	int SUNMatSpace_Sparse(Sundials_sunmatrixsparseLibrary.SUNMatrix A, LongBuffer lenrw, LongBuffer leniw);
	public static class SUNMatrix extends PointerType {
		public SUNMatrix(Pointer address) {
			super(address);
		}
		public SUNMatrix() {
			super();
		}
	};
	public static class SUNContext extends PointerType {
		public SUNContext(Pointer address) {
			super(address);
		}
		public SUNContext() {
			super();
		}
	};
	public static class FILE extends PointerType {
		public FILE(Pointer address) {
			super(address);
		}
		public FILE() {
			super();
		}
	};
	public static class N_Vector extends PointerType {
		public N_Vector(Pointer address) {
			super(address);
		}
		public N_Vector() {
			super();
		}
	};
}
