package cn.catarc.jsundials.sunlinsolsptfqmr;
import cn.catarc.jsundials.sunlinsolsptfqmr.Sundials_sunlinsolsptfqmrLibrary.N_Vector;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.PointerByReference;
import java.util.Arrays;
import java.util.List;
/**
 * ------------------------------------------<br>
 * SPTFQMR Implementation of SUNLinearSolver<br>
 * ------------------------------------------<br>
 * <i>native declaration : include\sunlinsol\sunlinsol_sptfqmr.h:13</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class _SUNLinearSolverContent_SPTFQMR extends Structure {
	public int maxl;
	public int pretype;
	public int zeroguess;
	public int numiters;
	/** C type : sunrealtype */
	public double resnorm;
	public int last_flag;
	/** C type : SUNATimesFn */
	public Pointer ATimes;
	/** C type : void* */
	public Pointer ATData;
	/** C type : SUNPSetupFn */
	public Pointer Psetup;
	/** C type : SUNPSolveFn */
	public Pointer Psolve;
	/** C type : void* */
	public Pointer PData;
	/** C type : N_Vector */
	public N_Vector s1;
	/** C type : N_Vector */
	public N_Vector s2;
	/** C type : N_Vector */
	public N_Vector r_star;
	/** C type : N_Vector */
	public N_Vector q;
	/** C type : N_Vector */
	public N_Vector d;
	/** C type : N_Vector */
	public N_Vector v;
	/** C type : N_Vector */
	public N_Vector p;
	/** C type : N_Vector* */
	public PointerByReference r;
	/** C type : N_Vector */
	public N_Vector u;
	/** C type : N_Vector */
	public N_Vector vtemp1;
	/** C type : N_Vector */
	public N_Vector vtemp2;
	/** C type : N_Vector */
	public N_Vector vtemp3;
	public _SUNLinearSolverContent_SPTFQMR() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("maxl", "pretype", "zeroguess", "numiters", "resnorm", "last_flag", "ATimes", "ATData", "Psetup", "Psolve", "PData", "s1", "s2", "r_star", "q", "d", "v", "p", "r", "u", "vtemp1", "vtemp2", "vtemp3");
	}
	public _SUNLinearSolverContent_SPTFQMR(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends _SUNLinearSolverContent_SPTFQMR implements Structure.ByReference {
		
	};
	public static class ByValue extends _SUNLinearSolverContent_SPTFQMR implements Structure.ByValue {
		
	};
}
