package cn.catarc.jsundials.sunlinsolspbcgs;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.LongByReference;
import java.nio.LongBuffer;
/**
 * JNA Wrapper for library <b>sundials_sunlinsolspbcgs</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface Sundials_sunlinsolspbcgsLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "sundials_sunlinsolspbcgs";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(Sundials_sunlinsolspbcgsLibrary.JNA_LIBRARY_NAME);
	public static final Sundials_sunlinsolspbcgsLibrary INSTANCE = (Sundials_sunlinsolspbcgsLibrary)Native.loadLibrary(Sundials_sunlinsolspbcgsLibrary.JNA_LIBRARY_NAME, Sundials_sunlinsolspbcgsLibrary.class);
	/** <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h</i> */
	public static final int SUNSPBCGS_MAXL_DEFAULT = (int)5;
	/**
	 * ---------------------------------------<br>
	 * Exported Functions for SUNLINSOL_SPBCGS<br>
	 * ---------------------------------------<br>
	 * Original signature : <code>SUNLinearSolver SUNLinSol_SPBCGS(N_Vector, int, int, SUNContext)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:45</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSol_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.N_Vector, int, int, cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNContext)} and {@link #SUNLinSol_SPBCGS(com.sun.jna.Pointer, int, int, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver SUNLinSol_SPBCGS(Pointer y, int pretype, int maxl, Pointer sunctx);
	/**
	 * ---------------------------------------<br>
	 * Exported Functions for SUNLINSOL_SPBCGS<br>
	 * ---------------------------------------<br>
	 * Original signature : <code>SUNLinearSolver SUNLinSol_SPBCGS(N_Vector, int, int, SUNContext)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:45</i>
	 */
	Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver SUNLinSol_SPBCGS(Sundials_sunlinsolspbcgsLibrary.N_Vector y, int pretype, int maxl, Sundials_sunlinsolspbcgsLibrary.SUNContext sunctx);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSol_SPBCGSSetPrecType(SUNLinearSolver, int)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:47</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSol_SPBCGSSetPrecType(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver, int)} and {@link #SUNLinSol_SPBCGSSetPrecType(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int SUNLinSol_SPBCGSSetPrecType(Pointer S, int pretype);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSol_SPBCGSSetPrecType(SUNLinearSolver, int)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:47</i>
	 */
	int SUNLinSol_SPBCGSSetPrecType(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S, int pretype);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSol_SPBCGSSetMaxl(SUNLinearSolver, int)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:49</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSol_SPBCGSSetMaxl(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver, int)} and {@link #SUNLinSol_SPBCGSSetMaxl(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int SUNLinSol_SPBCGSSetMaxl(Pointer S, int maxl);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSol_SPBCGSSetMaxl(SUNLinearSolver, int)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:49</i>
	 */
	int SUNLinSol_SPBCGSSetMaxl(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S, int maxl);
	/**
	 * Original signature : <code>SUNLinearSolver_Type SUNLinSolGetType_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:50</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSolGetType_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver)} and {@link #SUNLinSolGetType_SPBCGS(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNLinSolGetType_SPBCGS(Pointer S);
	/**
	 * Original signature : <code>SUNLinearSolver_Type SUNLinSolGetType_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:50</i>
	 */
	int SUNLinSolGetType_SPBCGS(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S);
	/**
	 * Original signature : <code>SUNLinearSolver_ID SUNLinSolGetID_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:51</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSolGetID_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver)} and {@link #SUNLinSolGetID_SPBCGS(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNLinSolGetID_SPBCGS(Pointer S);
	/**
	 * Original signature : <code>SUNLinearSolver_ID SUNLinSolGetID_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:51</i>
	 */
	int SUNLinSolGetID_SPBCGS(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSolInitialize_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:52</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSolInitialize_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver)} and {@link #SUNLinSolInitialize_SPBCGS(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNLinSolInitialize_SPBCGS(Pointer S);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSolInitialize_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:52</i>
	 */
	int SUNLinSolInitialize_SPBCGS(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSolSetATimes_SPBCGS(SUNLinearSolver, void*, SUNATimesFn)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:53</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSolSetATimes_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver, com.sun.jna.Pointer, com.sun.jna.Pointer)} and {@link #SUNLinSolSetATimes_SPBCGS(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNLinSolSetATimes_SPBCGS(Pointer S, Pointer A_data, Pointer ATimes);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSolSetATimes_SPBCGS(SUNLinearSolver, void*, SUNATimesFn)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:53</i>
	 */
	int SUNLinSolSetATimes_SPBCGS(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S, Pointer A_data, Pointer ATimes);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSolSetPreconditioner_SPBCGS(SUNLinearSolver, void*, SUNPSetupFn, SUNPSolveFn)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:56</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSolSetPreconditioner_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} and {@link #SUNLinSolSetPreconditioner_SPBCGS(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNLinSolSetPreconditioner_SPBCGS(Pointer S, Pointer P_data, Pointer Pset, Pointer Psol);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSolSetPreconditioner_SPBCGS(SUNLinearSolver, void*, SUNPSetupFn, SUNPSolveFn)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:56</i>
	 */
	int SUNLinSolSetPreconditioner_SPBCGS(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S, Pointer P_data, Pointer Pset, Pointer Psol);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSolSetScalingVectors_SPBCGS(SUNLinearSolver, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:60</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSolSetScalingVectors_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver, cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.N_Vector, cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.N_Vector)} and {@link #SUNLinSolSetScalingVectors_SPBCGS(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNLinSolSetScalingVectors_SPBCGS(Pointer S, Pointer s1, Pointer s2);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSolSetScalingVectors_SPBCGS(SUNLinearSolver, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:60</i>
	 */
	int SUNLinSolSetScalingVectors_SPBCGS(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S, Sundials_sunlinsolspbcgsLibrary.N_Vector s1, Sundials_sunlinsolspbcgsLibrary.N_Vector s2);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSolSetZeroGuess_SPBCGS(SUNLinearSolver, int)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:63</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSolSetZeroGuess_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver, int)} and {@link #SUNLinSolSetZeroGuess_SPBCGS(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int SUNLinSolSetZeroGuess_SPBCGS(Pointer S, int onoff);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSolSetZeroGuess_SPBCGS(SUNLinearSolver, int)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:63</i>
	 */
	int SUNLinSolSetZeroGuess_SPBCGS(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S, int onoff);
	/**
	 * Original signature : <code>int SUNLinSolSetup_SPBCGS(SUNLinearSolver, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:65</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSolSetup_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver, cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNMatrix)} and {@link #SUNLinSolSetup_SPBCGS(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNLinSolSetup_SPBCGS(Pointer S, Pointer A);
	/**
	 * Original signature : <code>int SUNLinSolSetup_SPBCGS(SUNLinearSolver, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:65</i>
	 */
	int SUNLinSolSetup_SPBCGS(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S, Sundials_sunlinsolspbcgsLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>int SUNLinSolSolve_SPBCGS(SUNLinearSolver, SUNMatrix, N_Vector, N_Vector, sunrealtype)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:66</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSolSolve_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver, cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNMatrix, cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.N_Vector, cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.N_Vector, double)} and {@link #SUNLinSolSolve_SPBCGS(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, double)} instead
	 */
	@Deprecated 
	int SUNLinSolSolve_SPBCGS(Pointer S, Pointer A, Pointer x, Pointer b, double tol);
	/**
	 * Original signature : <code>int SUNLinSolSolve_SPBCGS(SUNLinearSolver, SUNMatrix, N_Vector, N_Vector, sunrealtype)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:66</i>
	 */
	int SUNLinSolSolve_SPBCGS(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S, Sundials_sunlinsolspbcgsLibrary.SUNMatrix A, Sundials_sunlinsolspbcgsLibrary.N_Vector x, Sundials_sunlinsolspbcgsLibrary.N_Vector b, double tol);
	/**
	 * Original signature : <code>int SUNLinSolNumIters_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:69</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSolNumIters_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver)} and {@link #SUNLinSolNumIters_SPBCGS(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNLinSolNumIters_SPBCGS(Pointer S);
	/**
	 * Original signature : <code>int SUNLinSolNumIters_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:69</i>
	 */
	int SUNLinSolNumIters_SPBCGS(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S);
	/**
	 * Original signature : <code>sunrealtype SUNLinSolResNorm_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:70</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSolResNorm_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver)} and {@link #SUNLinSolResNorm_SPBCGS(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	double SUNLinSolResNorm_SPBCGS(Pointer S);
	/**
	 * Original signature : <code>sunrealtype SUNLinSolResNorm_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:70</i>
	 */
	double SUNLinSolResNorm_SPBCGS(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S);
	/**
	 * Original signature : <code>N_Vector SUNLinSolResid_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:71</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSolResid_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver)} and {@link #SUNLinSolResid_SPBCGS(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_sunlinsolspbcgsLibrary.N_Vector SUNLinSolResid_SPBCGS(Pointer S);
	/**
	 * Original signature : <code>N_Vector SUNLinSolResid_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:71</i>
	 */
	Sundials_sunlinsolspbcgsLibrary.N_Vector SUNLinSolResid_SPBCGS(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S);
	/**
	 * Original signature : <code>sunindextype SUNLinSolLastFlag_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:72</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSolLastFlag_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver)} and {@link #SUNLinSolLastFlag_SPBCGS(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNLinSolLastFlag_SPBCGS(Pointer S);
	/**
	 * Original signature : <code>sunindextype SUNLinSolLastFlag_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:72</i>
	 */
	long SUNLinSolLastFlag_SPBCGS(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSolSpace_SPBCGS(SUNLinearSolver, long long*, long long*)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:73</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSolSpace_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver, java.nio.LongBuffer, java.nio.LongBuffer)} and {@link #SUNLinSolSpace_SPBCGS(com.sun.jna.Pointer, com.sun.jna.ptr.LongByReference, com.sun.jna.ptr.LongByReference)} instead
	 */
	@Deprecated 
	int SUNLinSolSpace_SPBCGS(Pointer S, LongByReference lenrwLS, LongByReference leniwLS);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSolSpace_SPBCGS(SUNLinearSolver, long long*, long long*)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:73</i>
	 */
	int SUNLinSolSpace_SPBCGS(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S, LongBuffer lenrwLS, LongBuffer leniwLS);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSolFree_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:76</i><br>
	 * @deprecated use the safer methods {@link #SUNLinSolFree_SPBCGS(cn.catarc.jsundials.sunlinsolspbcgs.Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver)} and {@link #SUNLinSolFree_SPBCGS(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNLinSolFree_SPBCGS(Pointer S);
	/**
	 * Original signature : <code>SUNErrCode SUNLinSolFree_SPBCGS(SUNLinearSolver)</code><br>
	 * <i>native declaration : include\sunlinsol\sunlinsol_spbcgs.h:76</i>
	 */
	int SUNLinSolFree_SPBCGS(Sundials_sunlinsolspbcgsLibrary.SUNLinearSolver S);
	public static class SUNLinearSolver extends PointerType {
		public SUNLinearSolver(Pointer address) {
			super(address);
		}
		public SUNLinearSolver() {
			super();
		}
	};
	public static class SUNMatrix extends PointerType {
		public SUNMatrix(Pointer address) {
			super(address);
		}
		public SUNMatrix() {
			super();
		}
	};
	public static class SUNContext extends PointerType {
		public SUNContext(Pointer address) {
			super(address);
		}
		public SUNContext() {
			super();
		}
	};
	public static class N_Vector extends PointerType {
		public N_Vector(Pointer address) {
			super(address);
		}
		public N_Vector() {
			super();
		}
	};
}
