package cn.catarc.jsundials.sunmatrixdense;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.DoubleByReference;
import com.sun.jna.ptr.LongByReference;
import com.sun.jna.ptr.PointerByReference;
import java.nio.LongBuffer;
/**
 * JNA Wrapper for library <b>sundials_sunmatrixdense</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface Sundials_sunmatrixdenseLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "sundials_sunmatrixdense";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(Sundials_sunmatrixdenseLibrary.JNA_LIBRARY_NAME);
	public static final Sundials_sunmatrixdenseLibrary INSTANCE = (Sundials_sunmatrixdenseLibrary)Native.loadLibrary(Sundials_sunmatrixdenseLibrary.JNA_LIBRARY_NAME, Sundials_sunmatrixdenseLibrary.class);
	/**
	 * ---------------------------------------<br>
	 * Exported Functions for SUNMATRIX_DENSE<br>
	 * ---------------------------------------<br>
	 * Original signature : <code>SUNMatrix SUNDenseMatrix(sunindextype, sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:79</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix(long, long, cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNContext)} and {@link #SUNDenseMatrix(long, long, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_sunmatrixdenseLibrary.SUNMatrix SUNDenseMatrix(long M, long N, Pointer sunctx);
	/**
	 * ---------------------------------------<br>
	 * Exported Functions for SUNMATRIX_DENSE<br>
	 * ---------------------------------------<br>
	 * Original signature : <code>SUNMatrix SUNDenseMatrix(sunindextype, sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:79</i>
	 */
	Sundials_sunmatrixdenseLibrary.SUNMatrix SUNDenseMatrix(long M, long N, Sundials_sunmatrixdenseLibrary.SUNContext sunctx);
	/**
	 * Original signature : <code>void SUNDenseMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:82</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix_Print(cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix, com.sun.jna.ptr.PointerByReference)} and {@link #SUNDenseMatrix_Print(com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void SUNDenseMatrix_Print(Pointer A, Pointer outfile);
	/**
	 * Original signature : <code>void SUNDenseMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:82</i>
	 */
	void SUNDenseMatrix_Print(Sundials_sunmatrixdenseLibrary.SUNMatrix A, PointerByReference outfile);
	/**
	 * Original signature : <code>void SUNDenseMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:82</i>
	 */
	void SUNDenseMatrix_Print(Pointer A, PointerByReference outfile);
	/**
	 * Original signature : <code>sunindextype SUNDenseMatrix_Rows(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:84</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix_Rows(cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix)} and {@link #SUNDenseMatrix_Rows(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNDenseMatrix_Rows(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNDenseMatrix_Rows(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:84</i>
	 */
	long SUNDenseMatrix_Rows(Sundials_sunmatrixdenseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNDenseMatrix_Columns(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:85</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix_Columns(cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix)} and {@link #SUNDenseMatrix_Columns(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNDenseMatrix_Columns(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNDenseMatrix_Columns(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:85</i>
	 */
	long SUNDenseMatrix_Columns(Sundials_sunmatrixdenseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNDenseMatrix_LData(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:86</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix_LData(cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix)} and {@link #SUNDenseMatrix_LData(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNDenseMatrix_LData(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNDenseMatrix_LData(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:86</i>
	 */
	long SUNDenseMatrix_LData(Sundials_sunmatrixdenseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype* SUNDenseMatrix_Data(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:87</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix_Data(cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix)} and {@link #SUNDenseMatrix_Data(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	DoubleByReference SUNDenseMatrix_Data(Pointer A);
	/**
	 * Original signature : <code>sunrealtype* SUNDenseMatrix_Data(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:87</i>
	 */
	DoubleByReference SUNDenseMatrix_Data(Sundials_sunmatrixdenseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype** SUNDenseMatrix_Cols(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:88</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix_Cols(cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix)} and {@link #SUNDenseMatrix_Cols(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	PointerByReference SUNDenseMatrix_Cols(Pointer A);
	/**
	 * Original signature : <code>sunrealtype** SUNDenseMatrix_Cols(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:88</i>
	 */
	PointerByReference SUNDenseMatrix_Cols(Sundials_sunmatrixdenseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype* SUNDenseMatrix_Column(SUNMatrix, sunindextype)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:89</i><br>
	 * @deprecated use the safer methods {@link #SUNDenseMatrix_Column(cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix, long)} and {@link #SUNDenseMatrix_Column(com.sun.jna.Pointer, long)} instead
	 */
	@Deprecated 
	DoubleByReference SUNDenseMatrix_Column(Pointer A, long j);
	/**
	 * Original signature : <code>sunrealtype* SUNDenseMatrix_Column(SUNMatrix, sunindextype)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:89</i>
	 */
	DoubleByReference SUNDenseMatrix_Column(Sundials_sunmatrixdenseLibrary.SUNMatrix A, long j);
	/**
	 * Original signature : <code>SUNMatrix_ID SUNMatGetID_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:91</i><br>
	 * @deprecated use the safer methods {@link #SUNMatGetID_Dense(cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix)} and {@link #SUNMatGetID_Dense(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatGetID_Dense(Pointer A);
	/**
	 * Original signature : <code>SUNMatrix_ID SUNMatGetID_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:91</i>
	 */
	int SUNMatGetID_Dense(Sundials_sunmatrixdenseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNMatrix SUNMatClone_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:92</i><br>
	 * @deprecated use the safer methods {@link #SUNMatClone_Dense(cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix)} and {@link #SUNMatClone_Dense(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_sunmatrixdenseLibrary.SUNMatrix SUNMatClone_Dense(Pointer A);
	/**
	 * Original signature : <code>SUNMatrix SUNMatClone_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:92</i>
	 */
	Sundials_sunmatrixdenseLibrary.SUNMatrix SUNMatClone_Dense(Sundials_sunmatrixdenseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>void SUNMatDestroy_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:93</i><br>
	 * @deprecated use the safer methods {@link #SUNMatDestroy_Dense(cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix)} and {@link #SUNMatDestroy_Dense(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void SUNMatDestroy_Dense(Pointer A);
	/**
	 * Original signature : <code>void SUNMatDestroy_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:93</i>
	 */
	void SUNMatDestroy_Dense(Sundials_sunmatrixdenseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatZero_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:94</i><br>
	 * @deprecated use the safer methods {@link #SUNMatZero_Dense(cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix)} and {@link #SUNMatZero_Dense(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatZero_Dense(Pointer A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatZero_Dense(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:94</i>
	 */
	int SUNMatZero_Dense(Sundials_sunmatrixdenseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatCopy_Dense(SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:95</i><br>
	 * @deprecated use the safer methods {@link #SUNMatCopy_Dense(cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix, cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix)} and {@link #SUNMatCopy_Dense(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatCopy_Dense(Pointer A, Pointer B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatCopy_Dense(SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:95</i>
	 */
	int SUNMatCopy_Dense(Sundials_sunmatrixdenseLibrary.SUNMatrix A, Sundials_sunmatrixdenseLibrary.SUNMatrix B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAdd_Dense(sunrealtype, SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:96</i><br>
	 * @deprecated use the safer methods {@link #SUNMatScaleAdd_Dense(double, cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix, cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix)} and {@link #SUNMatScaleAdd_Dense(double, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatScaleAdd_Dense(double c, Pointer A, Pointer B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAdd_Dense(sunrealtype, SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:96</i>
	 */
	int SUNMatScaleAdd_Dense(double c, Sundials_sunmatrixdenseLibrary.SUNMatrix A, Sundials_sunmatrixdenseLibrary.SUNMatrix B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAddI_Dense(sunrealtype, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:98</i><br>
	 * @deprecated use the safer methods {@link #SUNMatScaleAddI_Dense(double, cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix)} and {@link #SUNMatScaleAddI_Dense(double, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatScaleAddI_Dense(double c, Pointer A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAddI_Dense(sunrealtype, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:98</i>
	 */
	int SUNMatScaleAddI_Dense(double c, Sundials_sunmatrixdenseLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatMatvec_Dense(SUNMatrix, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:99</i><br>
	 * @deprecated use the safer methods {@link #SUNMatMatvec_Dense(cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix, cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.N_Vector, cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.N_Vector)} and {@link #SUNMatMatvec_Dense(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatMatvec_Dense(Pointer A, Pointer x, Pointer y);
	/**
	 * Original signature : <code>SUNErrCode SUNMatMatvec_Dense(SUNMatrix, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:99</i>
	 */
	int SUNMatMatvec_Dense(Sundials_sunmatrixdenseLibrary.SUNMatrix A, Sundials_sunmatrixdenseLibrary.N_Vector x, Sundials_sunmatrixdenseLibrary.N_Vector y);
	/**
	 * Original signature : <code>SUNErrCode SUNMatSpace_Dense(SUNMatrix, long long*, long long*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:101</i><br>
	 * @deprecated use the safer methods {@link #SUNMatSpace_Dense(cn.catarc.jsundials.sunmatrixdense.Sundials_sunmatrixdenseLibrary.SUNMatrix, java.nio.LongBuffer, java.nio.LongBuffer)} and {@link #SUNMatSpace_Dense(com.sun.jna.Pointer, com.sun.jna.ptr.LongByReference, com.sun.jna.ptr.LongByReference)} instead
	 */
	@Deprecated 
	int SUNMatSpace_Dense(Pointer A, LongByReference lenrw, LongByReference leniw);
	/**
	 * Original signature : <code>SUNErrCode SUNMatSpace_Dense(SUNMatrix, long long*, long long*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_dense.h:101</i>
	 */
	int SUNMatSpace_Dense(Sundials_sunmatrixdenseLibrary.SUNMatrix A, LongBuffer lenrw, LongBuffer leniw);
	public static class SUNMatrix extends PointerType {
		public SUNMatrix(Pointer address) {
			super(address);
		}
		public SUNMatrix() {
			super();
		}
	};
	public static class SUNContext extends PointerType {
		public SUNContext(Pointer address) {
			super(address);
		}
		public SUNContext() {
			super();
		}
	};
	public static class FILE extends PointerType {
		public FILE(Pointer address) {
			super(address);
		}
		public FILE() {
			super();
		}
	};
	public static class N_Vector extends PointerType {
		public N_Vector(Pointer address) {
			super(address);
		}
		public N_Vector() {
			super();
		}
	};
}
