package cn.catarc.jsundials.core;
import cn.catarc.jsundials.core.Sundials_coreLibrary.SUNContext;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * A linear solver is a structure with an implementation-dependent<br>
 * 'content' field, and a pointer to a structure of linear solver<br>
 * operations corresponding to that implementation.<br>
 * <i>native declaration : include\sundials\sundials_linearsolver.h:74</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class _generic_SUNLinearSolver extends Structure {
	/** C type : void* */
	public Pointer content;
	/** C type : SUNLinearSolver_Ops */
	public cn.catarc.jsundials.core._generic_SUNLinearSolver_Ops.ByReference ops;
	/** C type : SUNContext */
	public SUNContext sunctx;
	public _generic_SUNLinearSolver() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("content", "ops", "sunctx");
	}
	/**
	 * @param content C type : void*<br>
	 * @param ops C type : SUNLinearSolver_Ops<br>
	 * @param sunctx C type : SUNContext
	 */
	public _generic_SUNLinearSolver(Pointer content, cn.catarc.jsundials.core._generic_SUNLinearSolver_Ops.ByReference ops, SUNContext sunctx) {
		super();
		this.content = content;
		this.ops = ops;
		this.sunctx = sunctx;
	}
	public _generic_SUNLinearSolver(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends _generic_SUNLinearSolver implements Structure.ByReference {
		
	};
	public static class ByValue extends _generic_SUNLinearSolver implements Structure.ByValue {
		
	};
}
