package cn.catarc.jsundials.sunmatrixband;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.DoubleByReference;
import com.sun.jna.ptr.LongByReference;
import com.sun.jna.ptr.PointerByReference;
import java.nio.LongBuffer;
/**
 * JNA Wrapper for library <b>sundials_sunmatrixband</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface Sundials_sunmatrixbandLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "sundials_sunmatrixband";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(Sundials_sunmatrixbandLibrary.JNA_LIBRARY_NAME);
	public static final Sundials_sunmatrixbandLibrary INSTANCE = (Sundials_sunmatrixbandLibrary)Native.loadLibrary(Sundials_sunmatrixbandLibrary.JNA_LIBRARY_NAME, Sundials_sunmatrixbandLibrary.class);
	/**
	 * ----------------------------------------<br>
	 * Exported  Functions for SUNMATRIX_BAND<br>
	 * ----------------------------------------<br>
	 * Original signature : <code>SUNMatrix SUNBandMatrix(sunindextype, sunindextype, sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:94</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix(long, long, long, cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNContext)} and {@link #SUNBandMatrix(long, long, long, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_sunmatrixbandLibrary.SUNMatrix SUNBandMatrix(long N, long mu, long ml, Pointer sunctx);
	/**
	 * ----------------------------------------<br>
	 * Exported  Functions for SUNMATRIX_BAND<br>
	 * ----------------------------------------<br>
	 * Original signature : <code>SUNMatrix SUNBandMatrix(sunindextype, sunindextype, sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:94</i>
	 */
	Sundials_sunmatrixbandLibrary.SUNMatrix SUNBandMatrix(long N, long mu, long ml, Sundials_sunmatrixbandLibrary.SUNContext sunctx);
	/**
	 * Original signature : <code>SUNMatrix SUNBandMatrixStorage(sunindextype, sunindextype, sunindextype, sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:97</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrixStorage(long, long, long, long, cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNContext)} and {@link #SUNBandMatrixStorage(long, long, long, long, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_sunmatrixbandLibrary.SUNMatrix SUNBandMatrixStorage(long N, long mu, long ml, long smu, Pointer sunctx);
	/**
	 * Original signature : <code>SUNMatrix SUNBandMatrixStorage(sunindextype, sunindextype, sunindextype, sunindextype, SUNContext)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:97</i>
	 */
	Sundials_sunmatrixbandLibrary.SUNMatrix SUNBandMatrixStorage(long N, long mu, long ml, long smu, Sundials_sunmatrixbandLibrary.SUNContext sunctx);
	/**
	 * Original signature : <code>void SUNBandMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:101</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_Print(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix, com.sun.jna.ptr.PointerByReference)} and {@link #SUNBandMatrix_Print(com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void SUNBandMatrix_Print(Pointer A, Pointer outfile);
	/**
	 * Original signature : <code>void SUNBandMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:101</i>
	 */
	void SUNBandMatrix_Print(Sundials_sunmatrixbandLibrary.SUNMatrix A, PointerByReference outfile);
	/**
	 * Original signature : <code>void SUNBandMatrix_Print(SUNMatrix, FILE*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:101</i>
	 */
	void SUNBandMatrix_Print(Pointer A, PointerByReference outfile);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_Rows(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:103</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_Rows(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNBandMatrix_Rows(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNBandMatrix_Rows(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_Rows(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:103</i>
	 */
	long SUNBandMatrix_Rows(Sundials_sunmatrixbandLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_Columns(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:104</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_Columns(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNBandMatrix_Columns(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNBandMatrix_Columns(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_Columns(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:104</i>
	 */
	long SUNBandMatrix_Columns(Sundials_sunmatrixbandLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_LowerBandwidth(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:105</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_LowerBandwidth(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNBandMatrix_LowerBandwidth(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNBandMatrix_LowerBandwidth(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_LowerBandwidth(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:105</i>
	 */
	long SUNBandMatrix_LowerBandwidth(Sundials_sunmatrixbandLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_UpperBandwidth(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:106</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_UpperBandwidth(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNBandMatrix_UpperBandwidth(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNBandMatrix_UpperBandwidth(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_UpperBandwidth(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:106</i>
	 */
	long SUNBandMatrix_UpperBandwidth(Sundials_sunmatrixbandLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_StoredUpperBandwidth(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:107</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_StoredUpperBandwidth(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNBandMatrix_StoredUpperBandwidth(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNBandMatrix_StoredUpperBandwidth(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_StoredUpperBandwidth(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:107</i>
	 */
	long SUNBandMatrix_StoredUpperBandwidth(Sundials_sunmatrixbandLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_LDim(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:108</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_LDim(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNBandMatrix_LDim(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNBandMatrix_LDim(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_LDim(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:108</i>
	 */
	long SUNBandMatrix_LDim(Sundials_sunmatrixbandLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_LData(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:109</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_LData(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNBandMatrix_LData(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	long SUNBandMatrix_LData(Pointer A);
	/**
	 * Original signature : <code>sunindextype SUNBandMatrix_LData(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:109</i>
	 */
	long SUNBandMatrix_LData(Sundials_sunmatrixbandLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype* SUNBandMatrix_Data(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:110</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_Data(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNBandMatrix_Data(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	DoubleByReference SUNBandMatrix_Data(Pointer A);
	/**
	 * Original signature : <code>sunrealtype* SUNBandMatrix_Data(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:110</i>
	 */
	DoubleByReference SUNBandMatrix_Data(Sundials_sunmatrixbandLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype** SUNBandMatrix_Cols(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:111</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_Cols(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNBandMatrix_Cols(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	PointerByReference SUNBandMatrix_Cols(Pointer A);
	/**
	 * Original signature : <code>sunrealtype** SUNBandMatrix_Cols(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:111</i>
	 */
	PointerByReference SUNBandMatrix_Cols(Sundials_sunmatrixbandLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>sunrealtype* SUNBandMatrix_Column(SUNMatrix, sunindextype)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:112</i><br>
	 * @deprecated use the safer methods {@link #SUNBandMatrix_Column(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix, long)} and {@link #SUNBandMatrix_Column(com.sun.jna.Pointer, long)} instead
	 */
	@Deprecated 
	DoubleByReference SUNBandMatrix_Column(Pointer A, long j);
	/**
	 * Original signature : <code>sunrealtype* SUNBandMatrix_Column(SUNMatrix, sunindextype)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:112</i>
	 */
	DoubleByReference SUNBandMatrix_Column(Sundials_sunmatrixbandLibrary.SUNMatrix A, long j);
	/**
	 * Original signature : <code>SUNMatrix_ID SUNMatGetID_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:114</i><br>
	 * @deprecated use the safer methods {@link #SUNMatGetID_Band(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNMatGetID_Band(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatGetID_Band(Pointer A);
	/**
	 * Original signature : <code>SUNMatrix_ID SUNMatGetID_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:114</i>
	 */
	int SUNMatGetID_Band(Sundials_sunmatrixbandLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNMatrix SUNMatClone_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:115</i><br>
	 * @deprecated use the safer methods {@link #SUNMatClone_Band(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNMatClone_Band(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	Sundials_sunmatrixbandLibrary.SUNMatrix SUNMatClone_Band(Pointer A);
	/**
	 * Original signature : <code>SUNMatrix SUNMatClone_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:115</i>
	 */
	Sundials_sunmatrixbandLibrary.SUNMatrix SUNMatClone_Band(Sundials_sunmatrixbandLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>void SUNMatDestroy_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:116</i><br>
	 * @deprecated use the safer methods {@link #SUNMatDestroy_Band(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNMatDestroy_Band(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void SUNMatDestroy_Band(Pointer A);
	/**
	 * Original signature : <code>void SUNMatDestroy_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:116</i>
	 */
	void SUNMatDestroy_Band(Sundials_sunmatrixbandLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatZero_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:117</i><br>
	 * @deprecated use the safer methods {@link #SUNMatZero_Band(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNMatZero_Band(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatZero_Band(Pointer A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatZero_Band(SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:117</i>
	 */
	int SUNMatZero_Band(Sundials_sunmatrixbandLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatCopy_Band(SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:118</i><br>
	 * @deprecated use the safer methods {@link #SUNMatCopy_Band(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix, cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNMatCopy_Band(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatCopy_Band(Pointer A, Pointer B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatCopy_Band(SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:118</i>
	 */
	int SUNMatCopy_Band(Sundials_sunmatrixbandLibrary.SUNMatrix A, Sundials_sunmatrixbandLibrary.SUNMatrix B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAdd_Band(sunrealtype, SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:119</i><br>
	 * @deprecated use the safer methods {@link #SUNMatScaleAdd_Band(double, cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix, cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNMatScaleAdd_Band(double, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatScaleAdd_Band(double c, Pointer A, Pointer B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAdd_Band(sunrealtype, SUNMatrix, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:119</i>
	 */
	int SUNMatScaleAdd_Band(double c, Sundials_sunmatrixbandLibrary.SUNMatrix A, Sundials_sunmatrixbandLibrary.SUNMatrix B);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAddI_Band(sunrealtype, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:121</i><br>
	 * @deprecated use the safer methods {@link #SUNMatScaleAddI_Band(double, cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix)} and {@link #SUNMatScaleAddI_Band(double, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatScaleAddI_Band(double c, Pointer A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatScaleAddI_Band(sunrealtype, SUNMatrix)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:121</i>
	 */
	int SUNMatScaleAddI_Band(double c, Sundials_sunmatrixbandLibrary.SUNMatrix A);
	/**
	 * Original signature : <code>SUNErrCode SUNMatMatvec_Band(SUNMatrix, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:122</i><br>
	 * @deprecated use the safer methods {@link #SUNMatMatvec_Band(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix, cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.N_Vector, cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.N_Vector)} and {@link #SUNMatMatvec_Band(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int SUNMatMatvec_Band(Pointer A, Pointer x, Pointer y);
	/**
	 * Original signature : <code>SUNErrCode SUNMatMatvec_Band(SUNMatrix, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:122</i>
	 */
	int SUNMatMatvec_Band(Sundials_sunmatrixbandLibrary.SUNMatrix A, Sundials_sunmatrixbandLibrary.N_Vector x, Sundials_sunmatrixbandLibrary.N_Vector y);
	/**
	 * Original signature : <code>SUNErrCode SUNMatSpace_Band(SUNMatrix, long long*, long long*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:123</i><br>
	 * @deprecated use the safer methods {@link #SUNMatSpace_Band(cn.catarc.jsundials.sunmatrixband.Sundials_sunmatrixbandLibrary.SUNMatrix, java.nio.LongBuffer, java.nio.LongBuffer)} and {@link #SUNMatSpace_Band(com.sun.jna.Pointer, com.sun.jna.ptr.LongByReference, com.sun.jna.ptr.LongByReference)} instead
	 */
	@Deprecated 
	int SUNMatSpace_Band(Pointer A, LongByReference lenrw, LongByReference leniw);
	/**
	 * Original signature : <code>SUNErrCode SUNMatSpace_Band(SUNMatrix, long long*, long long*)</code><br>
	 * <i>native declaration : include\sunmatrix\sunmatrix_band.h:123</i>
	 */
	int SUNMatSpace_Band(Sundials_sunmatrixbandLibrary.SUNMatrix A, LongBuffer lenrw, LongBuffer leniw);
	public static class SUNMatrix extends PointerType {
		public SUNMatrix(Pointer address) {
			super(address);
		}
		public SUNMatrix() {
			super();
		}
	};
	public static class SUNContext extends PointerType {
		public SUNContext(Pointer address) {
			super(address);
		}
		public SUNContext() {
			super();
		}
	};
	public static class FILE extends PointerType {
		public FILE(Pointer address) {
			super(address);
		}
		public FILE() {
			super();
		}
	};
	public static class N_Vector extends PointerType {
		public N_Vector(Pointer address) {
			super(address);
		}
		public N_Vector() {
			super();
		}
	};
}
